//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.CIMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMONLINK
    {
        public System.Guid CL_SN { get; set; }
        public string CL_LAN { get; set; }
        public string CL_TITLE { get; set; }
        public string CL_LINK { get; set; }
        public string CL_DESC { get; set; }
        public string CL_UPLOADLINK { get; set; }
        public string CL_KIND { get; set; }
        public Nullable<byte> CL_ORD { get; set; }
    }
}
