//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.CIMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM_FILE
    {
        public string OVC_PURCH { get; set; }
        public string OVC_KIND { get; set; }
        public string OVC_ITEM { get; set; }
        public string OVC_TIMES { get; set; }
        public string OVC_SUB { get; set; }
        public string OVC_ATTACH_NAME { get; set; }
        public string OVC_FILE_NAME { get; set; }
        public string OVC_UP_USER { get; set; }
    }
}
