//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.CIMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM_PUBLIC_BID
    {
        public string OVC_KEY { get; set; }
        public string OVC_PUB_KIND { get; set; }
        public string OVC_BID_SEC { get; set; }
        public string OVC_PURCH { get; set; }
        public string OVC_NPURCH { get; set; }
        public string OVC_PURCH_KIND { get; set; }
        public Nullable<decimal> ONB_BUDGET_MONEY { get; set; }
        public string OVC_BUDGET_RANGE { get; set; }
        public string OVC_BID_KIND { get; set; }
        public string OVC_DBID_KIND { get; set; }
        public Nullable<decimal> ONB_UNDER_MONEY { get; set; }
        public string OVC_OPEN_UNDER { get; set; }
        public Nullable<decimal> ONB_DBID_MONEY { get; set; }
        public string OVC_OPEN_DBID { get; set; }
        public Nullable<short> ONB_VEN_NUM { get; set; }
        public string OVC_VEN_NAME { get; set; }
        public string OVC_VEN_CST { get; set; }
        public string OVC_LAW58 { get; set; }
        public string OVC_LIMIT_RULE { get; set; }
        public string OVC_PUBLISH_DATE { get; set; }
        public string OVC_DBID_DATE { get; set; }
        public Nullable<decimal> ONB_UNDER_PLUS_BUDGET { get; set; }
        public Nullable<decimal> ONB_DBID_PLUS_UNDER { get; set; }
        public Nullable<decimal> ONB_DBID_PLUS_BUDGET { get; set; }
        public string OVC_DBID_DATE_IN { get; set; }
        public Nullable<decimal> ONB_JOIN_VEN { get; set; }
        public Nullable<short> ONB_SERIAL { get; set; }
        public string OVC_NOGET_VEN { get; set; }
        public Nullable<decimal> ONB_VEN_BID_MONEY { get; set; }
        public string OVC_OPEN_DATE { get; set; }
    }
}
