//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.CIMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM_PUBLIC_BID_99
    {
        public string OVC_KEY { get; set; }
        public string OVC_A { get; set; }
        public string OVC_B { get; set; }
        public string OVC_C { get; set; }
        public string OVC_D { get; set; }
        public string OVC_E { get; set; }
        public string OVC_F { get; set; }
        public string OVC_G { get; set; }
        public string OVC_H { get; set; }
        public string OVC_I { get; set; }
        public string OVC_J { get; set; }
        public string OVC_K { get; set; }
        public string OVC_L { get; set; }
        public Nullable<decimal> ONB_M { get; set; }
        public string OVC_N { get; set; }
        public string OVC_O { get; set; }
        public string OVC_P { get; set; }
        public Nullable<decimal> ONB_Q { get; set; }
        public string OVC_R { get; set; }
        public string OVC_S { get; set; }
        public Nullable<int> ONB_T { get; set; }
        public Nullable<int> ONB_U { get; set; }
        public Nullable<int> ONB_V { get; set; }
        public string OVC_W { get; set; }
        public string OVC_X { get; set; }
        public string OVC_Y { get; set; }
        public string OVC_Z { get; set; }
        public string OVC_AA { get; set; }
        public string OVC_AB { get; set; }
        public string OVC_AC { get; set; }
        public Nullable<decimal> ONB_AD { get; set; }
        public string OVC_AE { get; set; }
        public string OVC_AF { get; set; }
        public Nullable<decimal> ONB_AG { get; set; }
        public string OVC_AH { get; set; }
        public Nullable<decimal> ONB_AI { get; set; }
        public string OVC_AJ { get; set; }
        public string OVC_AK { get; set; }
        public string OVC_AL { get; set; }
        public string OVC_AM { get; set; }
        public string OVC_AN { get; set; }
        public Nullable<short> ONB_AO { get; set; }
        public string OVC_AP { get; set; }
        public string OVC_AQ { get; set; }
        public string OVC_AR { get; set; }
        public string OVC_AS { get; set; }
        public string OVC_AT { get; set; }
        public string OVC_AU { get; set; }
        public Nullable<short> ONB_AV { get; set; }
        public string OVC_AW { get; set; }
        public string OVC_AX { get; set; }
        public string OVC_AY { get; set; }
        public string OVC_AZ { get; set; }
        public Nullable<short> ONB_BA { get; set; }
        public string OVC_BB { get; set; }
        public string OVC_BC { get; set; }
        public string OVC_BD { get; set; }
        public string OVC_BE { get; set; }
        public Nullable<decimal> ONB_BF { get; set; }
        public string OVC_BG { get; set; }
        public string OVC_BH { get; set; }
        public Nullable<decimal> ONB_BI { get; set; }
    }
}
