//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.CIMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENAGENT
    {
        public string REGNO { get; set; }
        public string VEN_NAME { get; set; }
        public string VEN_DEPT { get; set; }
        public string VEN_CODE { get; set; }
        public string VEN_ADDR { get; set; }
        public string VEN_TEL { get; set; }
        public string VEN_FAX { get; set; }
        public string VEN_BOSS { get; set; }
        public string VEN_NAME_T { get; set; }
        public string VEN_ENAME_T { get; set; }
        public string VEN_CODE_T { get; set; }
        public string VEN_ADDR_T { get; set; }
        public string VEN_TEL_T { get; set; }
        public string VEN_FAX_T { get; set; }
        public string VEN_BOSS_T { get; set; }
        public string AUTH_DATE_E { get; set; }
        public string AUTH_RANGE { get; set; }
        public string AGENT_ITEM { get; set; }
        public string APPR_DATE_S { get; set; }
        public string APPR_DATE_E { get; set; }
        public string OVC_MEMO { get; set; }
        public string OVC_CREATE { get; set; }
        public string KEYIN { get; set; }
        public Nullable<System.DateTime> AUTH_DATE_S { get; set; }
    }
}
