//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using FCFDFE.Entity.GMModel;

    public partial class MTSEntities : DbContext
    {
        public MTSEntities()
            : base("name=MTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBGMT_BLD> TBGMT_BLD { get; set; }
        public virtual DbSet<TBGMT_BLD_MRPLOG> TBGMT_BLD_MRPLOG { get; set; }
        public virtual DbSet<TBGMT_EDF> TBGMT_EDF { get; set; }
        public virtual DbSet<TBGMT_EDF_DETAIL> TBGMT_EDF_DETAIL { get; set; }
        public virtual DbSet<TBGMT_EDF_DETAIL_MRPLOG> TBGMT_EDF_DETAIL_MRPLOG { get; set; }
        public virtual DbSet<TBGMT_EDF_MRPLOG> TBGMT_EDF_MRPLOG { get; set; }
        public virtual DbSet<TBGMT_ICR> TBGMT_ICR { get; set; }
        public virtual DbSet<TBGMT_IDR> TBGMT_IDR { get; set; }
        public virtual DbSet<TBGMT_IHO> TBGMT_IHO { get; set; }
        public virtual DbSet<TBGMT_IRD> TBGMT_IRD { get; set; }
        public virtual DbSet<TBGMT_IRD_CTN> TBGMT_IRD_CTN { get; set; }
        public virtual DbSet<TBGMT_IRD_DETAIL> TBGMT_IRD_DETAIL { get; set; }
        public virtual DbSet<TBGMT_IRD_MRPLOG> TBGMT_IRD_MRPLOG { get; set; }
        public virtual DbSet<TBGMT_CURRENCY> TBGMT_CURRENCY { get; set; }
        public virtual DbSet<TBGMT_DEPT_CDE> TBGMT_DEPT_CDE { get; set; }
        public virtual DbSet<TBGMT_DEPT_CLASS> TBGMT_DEPT_CLASS { get; set; }
        public virtual DbSet<TBGMT_PORTS> TBGMT_PORTS { get; set; }
        public virtual DbSet<TBGMT_ECL> TBGMT_ECL { get; set; }
        public virtual DbSet<TBGMT_ESO> TBGMT_ESO { get; set; }
        public virtual DbSet<TBGMT_ICR_MRPLOG> TBGMT_ICR_MRPLOG { get; set; }
        public virtual DbSet<TBGMT_ITEMLIST> TBGMT_ITEMLIST { get; set; }
        public virtual DbSet<TBGMT_ETR> TBGMT_ETR { get; set; }
        public virtual DbSet<TBGMT_EINN> TBGMT_EINN { get; set; }
        public virtual DbSet<TBGMT_INSRATE> TBGMT_INSRATE { get; set; }
        public virtual DbSet<TBGMT_COMPANY> TBGMT_COMPANY { get; set; }
        public virtual DbSet<TBGMT_IINF> TBGMT_IINF { get; set; }
        public virtual DbSet<TBGMT_EINF> TBGMT_EINF { get; set; }
        public virtual DbSet<TBGMT_IINN> TBGMT_IINN { get; set; }
        public virtual DbSet<TBGMT_CURRENCY_RATE> TBGMT_CURRENCY_RATE { get; set; }
        public virtual DbSet<TBGMT_CLAIM_RESERVE> TBGMT_CLAIM_RESERVE { get; set; }
        public virtual DbSet<TBGMT_BUDGET> TBGMT_BUDGET { get; set; }
        public virtual DbSet<TBGMT_CINF> TBGMT_CINF { get; set; }
        public virtual DbSet<TBGMT_ICS> TBGMT_ICS { get; set; }
        public virtual DbSet<TBGMT_CARRIAGE_DISCOUNT> TBGMT_CARRIAGE_DISCOUNT { get; set; }
        public virtual DbSet<TBGMT_TRANSFER_AIR_PRICE> TBGMT_TRANSFER_AIR_PRICE { get; set; }
        public virtual DbSet<TBGMT_TRANSFER_SEA_PRICE> TBGMT_TRANSFER_SEA_PRICE { get; set; }
        public virtual DbSet<TBGMT_TRANSFER_SEA_PRICE_100> TBGMT_TRANSFER_SEA_PRICE_100 { get; set; }
        public virtual DbSet<TBGMT_TRANSFER_SEA_PRICE_TMP> TBGMT_TRANSFER_SEA_PRICE_TMP { get; set; }
        public virtual DbSet<TBGMT_TOF> TBGMT_TOF { get; set; }
        public virtual DbSet<TBGMT_BLD_CARRIAGE> TBGMT_BLD_CARRIAGE { get; set; }
        public virtual DbSet<TBGMT_SCC> TBGMT_SCC { get; set; }
        public virtual DbSet<TBGMT_MRP> TBGMT_MRP { get; set; }
        public virtual DbSet<TBGMT_MRP_ITEM> TBGMT_MRP_ITEM { get; set; }
        public virtual DbSet<TBGMT_MRP_ITEM_LOG> TBGMT_MRP_ITEM_LOG { get; set; }
        public virtual DbSet<TBGMT_WRP> TBGMT_WRP { get; set; }
        public virtual DbSet<TBGMT_WRP_BLD> TBGMT_WRP_BLD { get; set; }
        public virtual DbSet<TBGMT_MRP_ITEM_DIFF> TBGMT_MRP_ITEM_DIFF { get; set; }
        public virtual DbSet<TBGMT_MRP_ITEM_TEMP_DIFF> TBGMT_MRP_ITEM_TEMP_DIFF { get; set; }
        public virtual DbSet<TBGMT_CLEARANCE> TBGMT_CLEARANCE { get; set; }
        public virtual DbSet<TBGMT_AIR_TRANSPORT> TBGMT_AIR_TRANSPORT { get; set; }
        public virtual DbSet<TBGMT_SEA_TRANSPORT> TBGMT_SEA_TRANSPORT { get; set; }
        public virtual DbSet<TBGMT_CLAIM> TBGMT_CLAIM { get; set; }
        public virtual DbSet<TBGMT_USER_GRP> TBGMT_USER_GRP { get; set; }
        public virtual DbSet<TBGMT_USERS> TBGMT_USERS { get; set; }
    
        public virtual int MRP_ITEM_DIFFERENCE2(string sECTION, string mRP_DATE, ObjectParameter rTN_MSG)
        {
            var sECTIONParameter = sECTION != null ?
                new ObjectParameter("SECTION", sECTION) :
                new ObjectParameter("SECTION", typeof(string));
    
            var mRP_DATEParameter = mRP_DATE != null ?
                new ObjectParameter("MRP_DATE", mRP_DATE) :
                new ObjectParameter("MRP_DATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MTSEntities.MRP_ITEM_DIFFERENCE2", sECTIONParameter, mRP_DATEParameter, rTN_MSG);
        }
    
        public virtual int MRP_ITEM_DIFF_SUMMARIZE(string mRP_DATE, ObjectParameter rTN_MSG)
        {
            var mRP_DATEParameter = mRP_DATE != null ?
                new ObjectParameter("MRP_DATE", mRP_DATE) :
                new ObjectParameter("MRP_DATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MTSEntities.MRP_ITEM_DIFF_SUMMARIZE", mRP_DATEParameter, rTN_MSG);
        }
    
        public virtual int MRP_ITEM_LOG_SUMMARIZE(string mRP_DATE, ObjectParameter rTN_MSG)
        {
            var mRP_DATEParameter = mRP_DATE != null ?
                new ObjectParameter("MRP_DATE", mRP_DATE) :
                new ObjectParameter("MRP_DATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MTSEntities.MRP_ITEM_LOG_SUMMARIZE", mRP_DATEParameter, rTN_MSG);
        }
    
        public virtual int MRP_LOG_UPD_USED_FLAG(string sECTION, string mRP_DATE, string pRI_DT, string tHIS_DT, ObjectParameter rTN_MSG)
        {
            var sECTIONParameter = sECTION != null ?
                new ObjectParameter("SECTION", sECTION) :
                new ObjectParameter("SECTION", typeof(string));
    
            var mRP_DATEParameter = mRP_DATE != null ?
                new ObjectParameter("MRP_DATE", mRP_DATE) :
                new ObjectParameter("MRP_DATE", typeof(string));
    
            var pRI_DTParameter = pRI_DT != null ?
                new ObjectParameter("PRI_DT", pRI_DT) :
                new ObjectParameter("PRI_DT", typeof(string));
    
            var tHIS_DTParameter = tHIS_DT != null ?
                new ObjectParameter("THIS_DT", tHIS_DT) :
                new ObjectParameter("THIS_DT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MTSEntities.MRP_LOG_UPD_USED_FLAG", sECTIONParameter, mRP_DATEParameter, pRI_DTParameter, tHIS_DTParameter, rTN_MSG);
        }
    
        public virtual int MRP_STA_SUMMARIZE(string mRP_DATE, ObjectParameter rTN_MSG)
        {
            var mRP_DATEParameter = mRP_DATE != null ?
                new ObjectParameter("MRP_DATE", mRP_DATE) :
                new ObjectParameter("MRP_DATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MTSEntities.MRP_STA_SUMMARIZE", mRP_DATEParameter, rTN_MSG);
        }
        public virtual DbSet<TBMDEPT> TBMDEPTs { get; set; }
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
    }
}
