//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_DEPT_CLASS
    {
        public string OVC_CLASS { get; set; }
        public string OVC_CLASS_NAME { get; set; }
        public Nullable<decimal> ONB_SORT { get; set; }
        public System.Guid OVC_DEPTCLA_SN { get; set; }
    }
}
