//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_TRANSFER_AIR_PRICE
    {
        public string OVC_YEAR { get; set; }
        public string OVC_PORT_TYPE { get; set; }
        public string OVC_START_PORT { get; set; }
        public string OVC_ARRIVE_PORT { get; set; }
        public decimal ONB_WEIGHT { get; set; }
        public decimal ONB_CARRIAGE { get; set; }
        public string ONB_CARRIAGE_CURRENCY { get; set; }
    }
}
