//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_CURRENCY_RATE
    {
        public string OVC_CURRENCY_CODE { get; set; }
        public decimal ONB_RATE { get; set; }
        public System.DateTime ODT_DATE { get; set; }
        public System.Guid OVC_RATE_SN { get; set; }
    }
}
