//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_USERS
    {
        public string OVC_LOGIN_ID { get; set; }
        public string OVC_USER_NAME { get; set; }
        public string OVC_USER_DESC { get; set; }
        public string OVC_USER_PASSWORD { get; set; }
        public string OVC_USER_DEPT_CDE { get; set; }
        public Nullable<System.DateTime> ODT_USER_LAST_ON_LINE { get; set; }
        public string OVC_USER_TEL { get; set; }
        public string OVC_USER_E_MAIL { get; set; }
        public string OVC_USER_STATUS { get; set; }
    }
}
