//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_CLAIM_RESERVE
    {
        public string OVC_RECLAIM_NO { get; set; }
        public string OVC_MILITARY_TYPE { get; set; }
        public Nullable<System.DateTime> OVC_APPLY_DATE { get; set; }
        public string OVC_BLD_NO { get; set; }
        public Nullable<System.DateTime> OVC_IMPORT_DATE { get; set; }
        public string OVC_INN_NO { get; set; }
        public string OVC_CLAIM_MSG_NO { get; set; }
        public string OVC_CLAIM_ITEM { get; set; }
        public string OVC_CLAIM_REASON { get; set; }
        public Nullable<decimal> ONB_RECEIVE { get; set; }
        public Nullable<decimal> ONB_ACTUAL_RECEIVE { get; set; }
        public Nullable<decimal> ONB_CLAIM_NUMBER { get; set; }
        public Nullable<decimal> ONB_CLAIM_AMOUNT { get; set; }
        public string OVC_CLAIM_CURRENCY { get; set; }
        public string OVC_APPROVE_STATUS { get; set; }
        public Nullable<decimal> ONB_COMPENSATION_AMOUNT { get; set; }
        public Nullable<System.DateTime> OVC_APPROVE_DATE { get; set; }
        public string OVC_CHEQUE_BANK { get; set; }
        public string OVC_CHEQUE_NO { get; set; }
        public string OVC_CHEQUE_TITLE { get; set; }
        public Nullable<System.DateTime> OVC_CHEQUE_DATE { get; set; }
        public string OVC_NOTE { get; set; }
        public Nullable<System.DateTime> OVC_CLAIM_DATE { get; set; }
        public string OVC_CLAIM_COM_MSG { get; set; }
        public Nullable<System.DateTime> OVC_CLAIM_COM_DATE { get; set; }
        public string OVC_PURCHASE_COM_MSG { get; set; }
        public Nullable<System.DateTime> OVC_PURCHASE_COM_DATE { get; set; }
        public string OVC_CLAIM_REV_MSG { get; set; }
        public Nullable<System.DateTime> OVC_CLAIM_REV_DATE { get; set; }
        public string OVC_PURCHASE_REV_MSG { get; set; }
        public Nullable<System.DateTime> OVC_PURCHASE_REV_DATE { get; set; }
        public string OVC_PURCHASE_MSG_NO { get; set; }
        public Nullable<System.DateTime> OVC_PURCHASE_DATE { get; set; }
        public string OVC_CLAIM_REASON_NOTE { get; set; }
        public Nullable<decimal> ONB_CLAIM_CURRENCY_RATE { get; set; }
        public Nullable<decimal> ONB_CLAIM_AMOUNT_NTD { get; set; }
        public string OVC_INS_COM_MSG { get; set; }
        public Nullable<decimal> ONB_COMPENSATION_CURRENCY_RATE { get; set; }
        public Nullable<decimal> ONB_COMPENSATION_AMOUNT_NTD { get; set; }
        public string OVC_COMPENSATION_CURRENCY { get; set; }
        public Nullable<decimal> ONB_CLAIM_BREAK { get; set; }
        public System.Guid RECLAIM_SN { get; set; }
        public string OVC_CREATE_ID { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
        public Nullable<System.DateTime> ODT_MODIFY_DATE { get; set; }
        public Nullable<System.DateTime> ODT_CLAIM_DATE { get; set; }
    }
}
