//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_EDF
    {
        public string OVC_EDF_NO { get; set; }
        public string OVC_PURCH_NO { get; set; }
        public string OVC_START_PORT { get; set; }
        public string OVC_ARRIVE_PORT { get; set; }
        public string OVC_DEPT_CDE { get; set; }
        public Nullable<System.DateTime> ODT_RECEIVE_DATE { get; set; }
        public string OVC_REQ_DEPT_CDE { get; set; }
        public string OVC_CON_CHI_ADDRESS { get; set; }
        public string OVC_CON_ENG_ADDRESS { get; set; }
        public string OVC_CON_TEL { get; set; }
        public string OVC_CON_FAX { get; set; }
        public string OVC_NP_CHI_ADDRESS { get; set; }
        public string OVC_NP_ENG_ADDRESS { get; set; }
        public string OVC_NP_TEL { get; set; }
        public string OVC_NP_FAX { get; set; }
        public string OVC_ANP_CHI_ADDRESS { get; set; }
        public string OVC_ANP_ENG_ADDRESS { get; set; }
        public string OVC_ANP_TEL { get; set; }
        public string OVC_ANP_FAX { get; set; }
        public string OVC_PAYMENT_TYPE { get; set; }
        public string OVC_NOTE { get; set; }
        public string OVC_IS_STRATEGY { get; set; }
        public Nullable<System.DateTime> ODT_VALIDITY_DATE { get; set; }
        public string OVC_LICENSE_NO { get; set; }
        public string OVC_REVIEW_STATUS { get; set; }
        public string OVC_REVIEW_LOGIN_ID { get; set; }
        public string OVC_SHIP_FROM { get; set; }
        public Nullable<System.DateTime> ODT_REVIEW_DATE { get; set; }
        public string OVC_BLD_NO { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public string OVC_ANP_ENG_ADDRESS2 { get; set; }
        public string OVC_ANP_TEL2 { get; set; }
        public string OVC_ANP_FAX2 { get; set; }
        public string OVC_IS_PAY { get; set; }
        public System.Guid EDF_SN { get; set; }
        public string OVC_DELIVER_NAME { get; set; }
        public string OVC_DELIVER_MILITARY_LINE { get; set; }
        public string OVC_DELIVER_MOBILE { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
        public string OVC_IS_RISK { get; set; }
        public string OVC_IS_ALERTNESS { get; set; }
    }
}
