//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_BLD_MRPLOG
    {
        public string LOG_LOGIN_ID { get; set; }
        public System.DateTime LOG_TIME { get; set; }
        public string LOG_EVENT { get; set; }
        public string OVC_BLD_NO { get; set; }
        public string OVC_SHIP_COMPANY { get; set; }
        public string OVC_SEA_OR_AIR { get; set; }
        public string OVC_SHIP_NAME { get; set; }
        public string OVC_VOYAGE { get; set; }
        public Nullable<System.DateTime> ODT_START_DATE { get; set; }
        public string OVC_START_PORT { get; set; }
        public string OVC_LAST_START_PORT { get; set; }
        public Nullable<System.DateTime> ODT_LAST_START_DATE { get; set; }
        public Nullable<System.DateTime> ODT_PLN_ARRIVE_DATE { get; set; }
        public Nullable<System.DateTime> ODT_ACT_ARRIVE_DATE { get; set; }
        public string OVC_ARRIVE_PORT { get; set; }
        public Nullable<decimal> ONB_QUANITY { get; set; }
        public string OVC_QUANITY_UNIT { get; set; }
        public Nullable<decimal> ONB_VOLUME { get; set; }
        public string OVC_VOLUME_UNIT { get; set; }
        public Nullable<decimal> ONB_WEIGHT { get; set; }
        public string OVC_WEIGHT_UNIT { get; set; }
        public Nullable<decimal> ONB_CARRIAGE { get; set; }
        public string ONB_CARRIAGE_CURRENCY { get; set; }
        public string OVC_ITEM_TYPE { get; set; }
        public string OVC_MILITARY_TYPE { get; set; }
        public string OVC_CONTRACT_AIRLINE { get; set; }
        public Nullable<decimal> ONB_DANGER_PRO_COST { get; set; }
        public string ONB_DANGER_PRO_CURRENCY { get; set; }
        public string OVC_STATUS { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public string OVC_PASS_TPEKHH { get; set; }
        public Nullable<decimal> ONB_ON_SHIP_VOLUME { get; set; }
        public Nullable<decimal> ONB_OLD_QUANITY { get; set; }
        public Nullable<decimal> ONB_OLD_VOLUME { get; set; }
        public Nullable<decimal> ONB_OLD_WEIGHT { get; set; }
        public string OVC_CREATE_TYPE { get; set; }
        public string OVC_IS_CHARGE { get; set; }
        public Nullable<decimal> ONB_ITEM_VALUE { get; set; }
        public string ONB_CARRIAGE_CURRENCY_I { get; set; }
        public string OVC_PAYMENT_TYPE { get; set; }
        public Nullable<System.DateTime> REAL_START_DATE { get; set; }
        public Nullable<decimal> REAL_VOLUME { get; set; }
        public Nullable<decimal> REAL_WEIGHT { get; set; }
        public Nullable<decimal> ONB_VOLUME_OLD { get; set; }
        public Nullable<decimal> ONB_WEIGHT_OLD { get; set; }
        public Nullable<decimal> REAL_VOLUME_OLD { get; set; }
        public Nullable<decimal> REAL_WEIGHT_OLD { get; set; }
        public string OVC_ARRIVE_PORT_OLD { get; set; }
        public string OVC_START_PORT_OLD { get; set; }
        public Nullable<System.DateTime> REAL_START_DATE_OLD { get; set; }
        public string DIFF_USED { get; set; }
        public string DIFF_YYYYMM { get; set; }
        public string OVC_MILITARY_TYPE_OLD { get; set; }
        public System.Guid MRPLOG_SN { get; set; }
        public Nullable<byte> OVC_IS_SECURITY { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
        public string ONB_DANGER_PRO { get; set; }
    }
}
