//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_INSRATE
    {
        public string OVC_INS_NAME { get; set; }
        public decimal OVC_INS_RATE { get; set; }
        public Nullable<System.DateTime> ODT_START_DATE { get; set; }
        public Nullable<System.DateTime> ODT_END_DATE { get; set; }
        public Nullable<decimal> ONB_SORT { get; set; }
        public System.Guid INSRATE_SN { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_CREATE_ID { get; set; }
        public Nullable<System.DateTime> ODT_MODIFY_DATE { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
        public string OVC_INSCOMPNAY { get; set; }
        public Nullable<System.Guid> OVC_CO_SN { get; set; }
        public string OVC_INS_NAME_1 { get; set; }
        public Nullable<decimal> OVC_INS_RATE_1 { get; set; }
        public string OVC_INS_NAME_2 { get; set; }
        public Nullable<decimal> OVC_INS_RATE_2 { get; set; }
        public string OVC_INS_NAME_3 { get; set; }
        public Nullable<decimal> OVC_INS_RATE_3 { get; set; }
        public string OVC_INS_NAME_4 { get; set; }
        public Nullable<decimal> OVC_INS_RATE_4 { get; set; }
    }
}
