//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_EINF
    {
        public string OVC_INF_NO { get; set; }
        public string OVC_GIST { get; set; }
        public string OVC_BUDGET { get; set; }
        public string OVC_PURPOSE_TYPE { get; set; }
        public Nullable<decimal> ONB_AMOUNT { get; set; }
        public string OVC_BUDGET_INF_NO { get; set; }
        public string OVC_INV_NO { get; set; }
        public Nullable<System.DateTime> ODT_INV_DATE { get; set; }
        public string OVC_NOTE { get; set; }
        public string OVC_PLN_CONTENT { get; set; }
        public string OVC_IS_PAID { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public Nullable<System.DateTime> ODT_APPLY_DATE { get; set; }
        public string SIGNNO { get; set; }
        public System.Guid EINF_SN { get; set; }
        public Nullable<System.Guid> CO_SN { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
    }
}
