//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_TOF
    {
        public string OVC_TOF_NO { get; set; }
        public string OVC_MILITARY_TYPE { get; set; }
        public string OVC_IE_TYPE { get; set; }
        public string OVC_BUDGET { get; set; }
        public string OVC_PURPOSE_TYPE { get; set; }
        public string OVC_ABSTRACT { get; set; }
        public Nullable<decimal> ONB_AMOUNT { get; set; }
        public string OVC_NOTE { get; set; }
        public string OVC_PLN_CONTENT { get; set; }
        public string OVC_SECTION { get; set; }
        public string OVC_APPLY_ID { get; set; }
        public System.DateTime ODT_APPLY_DATE { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_IS_PAID { get; set; }
        public string OVC_PAID_ID { get; set; }
        public Nullable<System.DateTime> ODT_PAID_DATE { get; set; }
        public string OVC_BUDGET_INF_NO { get; set; }
        public Nullable<decimal> ISLOCK { get; set; }
        public string SIGNNO { get; set; }
        public Nullable<System.DateTime> SIGN_DATE { get; set; }
    }
}
