//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_CLAIM
    {
        public string OVC_CLAIM_NO { get; set; }
        public string OVC_MILITARY_TYPE { get; set; }
        public string OVC_PURCH_NO { get; set; }
        public string OVC_INN_NO { get; set; }
        public Nullable<System.DateTime> ODT_CLAIM_DATE { get; set; }
        public string OVC_CLAIM_MSG_NO { get; set; }
        public string OVC_CLAIM_ITEM { get; set; }
        public Nullable<decimal> ONB_CLAIM_NUMBER { get; set; }
        public Nullable<decimal> ONB_CLAIM_AMOUNT { get; set; }
        public string OVC_CLAIM_CURRENCY { get; set; }
        public string OVC_CLAIM_CONDITION { get; set; }
        public string OVC_CLAIM_REASON { get; set; }
        public Nullable<System.DateTime> OVC_COMPENSATION_DATE { get; set; }
        public string OVC_COMPENSATION_MSG_NO { get; set; }
        public Nullable<decimal> ONB_COMPENSATION_NUMBER { get; set; }
        public string OVC_NOTE { get; set; }
        public string OVC_IS_COMPENSATED { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public Nullable<System.DateTime> ODT_RECEIVE_DATE { get; set; }
        public string OVC_ISSU_NO { get; set; }
        public string OVC_BLD_NO { get; set; }
        public string GET_FILE { get; set; }
        public System.Guid CLAIM_SN { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
        public Nullable<decimal> ONB_COMPENSATION_AMOUNT { get; set; }
        public string OVC_COMPENSATION_CURRENCY { get; set; }
    }
}
