//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_ICR_MRPLOG
    {
        public string LOG_LOGIN_ID { get; set; }
        public System.DateTime LOG_TIME { get; set; }
        public string LOG_EVENT { get; set; }
        public string OVC_BLD_NO { get; set; }
        public string OVC_PURCH_NO { get; set; }
        public string OVC_CHI_NAME { get; set; }
        public string OVC_RECEIVE_DEPT_CODE { get; set; }
        public Nullable<System.DateTime> ODT_RECEIVE_INF_DATE { get; set; }
        public Nullable<System.DateTime> ODT_IMPORT_DATE { get; set; }
        public Nullable<System.DateTime> ODT_ABROAD_CUSTOM_DATE { get; set; }
        public Nullable<System.DateTime> ODT_CHANGE_BLD_DATE { get; set; }
        public Nullable<System.DateTime> ODT_CUSTOM_DATE { get; set; }
        public string OVC_TRANS_TYPE { get; set; }
        public Nullable<System.DateTime> ODT_PASS_CUSTOM_DATE { get; set; }
        public Nullable<System.DateTime> ODT_UNPACKING_DATE { get; set; }
        public Nullable<System.DateTime> ODT_TRANSFER_DATE { get; set; }
        public Nullable<System.DateTime> ODT_RECEIVE_DATE { get; set; }
        public string OVC_NOTE { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public string DIFF_USED { get; set; }
        public string DIFF_YYYYMM { get; set; }
        public Nullable<System.DateTime> ODT_TRANSFER_DATE_OLD { get; set; }
        public string OVC_PURCH_NO_OLD { get; set; }
        public System.Guid OVC_ICRMRPLOG_SN { get; set; }
    }
}
