//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_IHO
    {
        public string OVC_IHO_NO { get; set; }
        public string OVC_INLAND_TRANS_TYPE { get; set; }
        public string OVC_START_PLACE { get; set; }
        public string OVC_ARRIVE_PLACE { get; set; }
        public Nullable<System.DateTime> ODT_START_DATE { get; set; }
        public Nullable<System.DateTime> ODT_ARRIVE_DATE { get; set; }
        public string OVC_RECEIVE_DEPT_CDE { get; set; }
        public string OVC_TRANSER_DEPT_CDE { get; set; }
        public Nullable<decimal> ONB_OVERFLOW { get; set; }
        public Nullable<decimal> ONB_LESS { get; set; }
        public Nullable<decimal> ONB_ACTUAL_RECEIVE { get; set; }
        public Nullable<decimal> ONB_BROKEN { get; set; }
        public string OVC_NOTE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public Nullable<decimal> ONB_QUANITY { get; set; }
        public string OVC_QUANITY_UNIT { get; set; }
        public Nullable<decimal> ONB_VOLUME { get; set; }
        public string OVC_VOLUME_UNIT { get; set; }
        public Nullable<decimal> ONB_WEIGHT { get; set; }
        public string OVC_WEIGHT_UNIT { get; set; }
        public string OVC_SHIP_NAME { get; set; }
        public string OVC_VOYAGE { get; set; }
        public System.Guid OVC_IHO_SN { get; set; }
    }
}
