//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_EINN
    {
        public string OVC_EINN_NO { get; set; }
        public string OVC_EDF_NO { get; set; }
        public string OVC_INS_CONDITION { get; set; }
        public Nullable<decimal> ONB_INS_RATE { get; set; }
        public Nullable<decimal> ONB_ITEM_VALUE { get; set; }
        public string ONB_CARRIAGE_CURRENCY { get; set; }
        public Nullable<decimal> ONB_INS_AMOUNT { get; set; }
        public string ONB_CARRIAGE_CURRENCY2 { get; set; }
        public Nullable<System.DateTime> ODT_INS_DATE { get; set; }
        public string OVC_PAYMENT_TYPE { get; set; }
        public string OVC_MILITARY_TYPE { get; set; }
        public string OVC_CESSION_NO { get; set; }
        public string OVC_INS_NO { get; set; }
        public string OVC_INF_NO { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public Nullable<decimal> OVC_FINAL_INS_AMOUNT { get; set; }
        public System.Guid EINN_SN { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
    }
}
