//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_IRD
    {
        public string OVC_BLD_NO { get; set; }
        public Nullable<System.DateTime> ODT_RECEIVE_DATE { get; set; }
        public Nullable<System.DateTime> ODT_RECEIVE_DATA_DATE { get; set; }
        public Nullable<System.DateTime> ODT_ARRIVE_PORT_DATE { get; set; }
        public Nullable<System.DateTime> ODT_CLEAR_DATE { get; set; }
        public Nullable<System.DateTime> ODT_PUT_FILE_DATE { get; set; }
        public Nullable<decimal> ONB_BROKEN { get; set; }
        public Nullable<decimal> ONB_ACTUAL_RECEIVE { get; set; }
        public Nullable<decimal> ONB_OVERFLOW { get; set; }
        public Nullable<decimal> ONB_LESS { get; set; }
        public string OVC_NOTE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CONTAINER_NO { get; set; }
        public System.Guid OVC_IRD_SN { get; set; }
    }
}
