//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_ECL
    {
        public string OVC_BLD_NO { get; set; }
        public string OVC_CLASS_CDE { get; set; }
        public string OVC_CLASS_NAME { get; set; }
        public string OVC_ECL_NO { get; set; }
        public string OVC_EXP_TYPE { get; set; }
        public string OVC_SHIP_CDE { get; set; }
        public string OVC_PACK_NO { get; set; }
        public Nullable<System.DateTime> ODT_EXP_DATE { get; set; }
        public string OVC_STORED_PLACE { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public System.Guid ECL_SN { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
    }
}
