//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_ESO
    {
        public string OVC_EDF_NO { get; set; }
        public string OVC_PURCH_MSG_NO1 { get; set; }
        public string OVC_PURCH_MSG_NO2 { get; set; }
        public string OVC_PURCH_MSG_NO3 { get; set; }
        public string OVC_SHIP_COMPANY { get; set; }
        public string OVC_SO_NO { get; set; }
        public string OVC_BLD_NO { get; set; }
        public string OVC_SHIP_NAME { get; set; }
        public string OVC_VOYAGE { get; set; }
        public string OVC_CONTAINER_TYPE { get; set; }
        public Nullable<System.DateTime> ODT_STORED_DATE { get; set; }
        public Nullable<System.DateTime> ODT_START_DATE { get; set; }
        public Nullable<System.DateTime> ODT_ACT_ARRIVE_DATE { get; set; }
        public string OVC_CUSTOM_CLR_PLACE { get; set; }
        public Nullable<System.DateTime> ODT_CUSTOM_CLR_DATE { get; set; }
        public string OVC_STORED_COMPANY { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public string OVC_OLD_BLD_NO { get; set; }
        public string OVC_PROCESS_NO1 { get; set; }
        public string OVC_PROCESS_NO2 { get; set; }
        public string OVC_PROCESS_NO3 { get; set; }
        public Nullable<decimal> ONB_20_COUNT { get; set; }
        public Nullable<decimal> ONB_40_COUNT { get; set; }
        public Nullable<decimal> ONB_45_COUNT { get; set; }
        public string OVC_BLD_NO_EP1 { get; set; }
        public System.Guid ESO_SN { get; set; }
        public Nullable<System.Guid> EDF_SN { get; set; }
        public Nullable<System.Guid> BLD_SN { get; set; }
    }
}
