//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_IRD_DETAIL
    {
        public string OVC_BLD_NO { get; set; }
        public string OVC_DEPT_CDE { get; set; }
        public string OVC_BOX_NO { get; set; }
        public string OVC_IHO_NO { get; set; }
        public decimal ONB_ACTUAL_RECEIVE { get; set; }
        public decimal ONB_OVERFLOW { get; set; }
        public decimal ONB_LESS { get; set; }
        public decimal ONB_BROKEN { get; set; }
        public string OVC_PURCH_NO { get; set; }
        public System.Guid OVC_IRDDETAIL_SN { get; set; }
    }
}
