//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_ETR
    {
        public string OVC_BLD_NO { get; set; }
        public Nullable<System.DateTime> ODT_REQUIRE_DATE { get; set; }
        public string OVC_REQUIRE_MSG_NO { get; set; }
        public Nullable<System.DateTime> ODT_RECEIVE_DATE { get; set; }
        public string OVC_RECEIVE_MSG_NO { get; set; }
        public Nullable<System.DateTime> ODT_PROCESS_DATE { get; set; }
        public string OVC_PROCESS_MSG_NO { get; set; }
        public Nullable<System.DateTime> ODT_STRATEGY_PROCESS_DATE { get; set; }
        public Nullable<System.DateTime> ODT_TEL_DATE { get; set; }
        public Nullable<System.DateTime> ODT_PASS_DATE { get; set; }
        public Nullable<System.DateTime> ODT_SHIP_START_DATE { get; set; }
        public Nullable<System.DateTime> ODT_RETURN_DATE { get; set; }
        public string OVC_DELAY_DESCRIPTION { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public System.Guid ETR_SN { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
    }
}
