//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_SCC
    {
        public string OVC_BLD_NO { get; set; }
        public Nullable<System.DateTime> ODT_ACQUIRE_DATE { get; set; }
        public Nullable<System.DateTime> ODT_RETURN_DATE { get; set; }
        public string OVC_NOTE_CENTER { get; set; }
        public string OVC_NOTE_COMPANY { get; set; }
        public Nullable<decimal> ONB_SHOW { get; set; }
    }
}
