//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_MRP_ITEM
    {
        public string OVC_SECTION { get; set; }
        public System.DateTime ODT_MONTH_DATE { get; set; }
        public string OVC_MILITARY { get; set; }
        public string OVC_IE { get; set; }
        public Nullable<decimal> ONB_BLD_M { get; set; }
        public Nullable<decimal> ONB_QUANITY_M { get; set; }
        public Nullable<decimal> ONB_WEIGHT_M { get; set; }
        public Nullable<decimal> ONB_VOLUME_M { get; set; }
        public Nullable<decimal> ONB_BLD_C { get; set; }
        public Nullable<decimal> ONB_QUANITY_C { get; set; }
        public Nullable<decimal> ONB_WEIGHT_C { get; set; }
        public Nullable<decimal> ONB_VOLUME_C { get; set; }
        public Nullable<decimal> ONB_BLD_O { get; set; }
        public Nullable<decimal> ONB_QUANITY_O { get; set; }
        public Nullable<decimal> ONB_WEIGHT_O { get; set; }
        public Nullable<decimal> ONB_VOLUME_O { get; set; }
        public string YEAR { get; set; }
        public Nullable<System.DateTime> ODT_MODIFY_DATE { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
        public System.Guid MRP_ITEM_SN { get; set; }
    }
}
