//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_WRP
    {
        public string OVC_SECTION { get; set; }
        public System.DateTime ODT_WEEK_DATE { get; set; }
        public Nullable<decimal> ONB_SHIP_AIR { get; set; }
        public Nullable<decimal> ONB_SHIP_SEA { get; set; }
        public Nullable<decimal> ONB_BLD_AIR { get; set; }
        public Nullable<decimal> ONB_BLD_SEA { get; set; }
        public Nullable<decimal> ONB_20_COUNT { get; set; }
        public Nullable<decimal> ONB_40_COUNT { get; set; }
        public Nullable<decimal> ONB_45_COUNT { get; set; }
        public Nullable<decimal> ONB_QUANITY { get; set; }
        public Nullable<decimal> ONB_WEIGHT { get; set; }
        public Nullable<decimal> ONB_VOLUME { get; set; }
        public Nullable<decimal> ONB_TRANS_DEFAULT { get; set; }
        public Nullable<decimal> ONB_TRANS_SUPPLIER { get; set; }
        public Nullable<decimal> ONB_TRANS_TRAIN { get; set; }
        public string OVC_LOGIN_ID { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
    }
}
