//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_AIR_TRANSPORT
    {
        public System.Guid AT_SN { get; set; }
        public System.Guid CO_SN { get; set; }
        public string OVC_START_PORT { get; set; }
        public string ONB_CARRIAGE_CURRENCY { get; set; }
        public Nullable<System.DateTime> ODT_START_DATE { get; set; }
        public Nullable<System.DateTime> ODT_END_DATE { get; set; }
        public string OVC_IMPORT_EXPORT_1 { get; set; }
        public Nullable<decimal> ONB_DISCOUNT_1 { get; set; }
        public Nullable<decimal> ONB_M_RATE_1 { get; set; }
        public Nullable<decimal> ONB_AS_N_RATE_1 { get; set; }
        public Nullable<decimal> ONB_N_RATE_1 { get; set; }
        public Nullable<decimal> ONB_AS_45_KG_1 { get; set; }
        public Nullable<decimal> ONB_PLUS_45_KG_1 { get; set; }
        public Nullable<decimal> ONB_AS_100_KG_1 { get; set; }
        public Nullable<decimal> ONB_PLUS_100_KG_1 { get; set; }
        public Nullable<decimal> ONB_AS_300_KG_1 { get; set; }
        public Nullable<decimal> ONB_PLUS_300_KG_1 { get; set; }
        public Nullable<decimal> ONB_AS_500_KG_1 { get; set; }
        public Nullable<decimal> ONB_PLUS_500_KG_1 { get; set; }
        public Nullable<decimal> ONB_EUR_BLD_QUANTITY_1 { get; set; }
        public Nullable<decimal> ONB_EUR_DANGER_PRO_COST_1 { get; set; }
        public Nullable<decimal> ONB_EUR_FIN_DANGER_PRO_COST_1 { get; set; }
        public Nullable<decimal> ONB_USA_BLD_QUANTITY_1 { get; set; }
        public Nullable<decimal> ONB_USA_DANGER_PRO_COST_1 { get; set; }
        public Nullable<decimal> ONB_USA_FIN_DANGER_PRO_COST_1 { get; set; }
        public string OVC_IMPORT_EXPORT_2 { get; set; }
        public Nullable<decimal> ONB_DISCOUNT_2 { get; set; }
        public Nullable<decimal> ONB_M_RATE_2 { get; set; }
        public Nullable<decimal> ONB_AS_N_RATE_2 { get; set; }
        public Nullable<decimal> ONB_N_RATE_2 { get; set; }
        public Nullable<decimal> ONB_AS_45_KG_2 { get; set; }
        public Nullable<decimal> ONB_PLUS_45_KG_2 { get; set; }
        public Nullable<decimal> ONB_AS_100_KG_2 { get; set; }
        public Nullable<decimal> ONB_PLUS_100_KG_2 { get; set; }
        public Nullable<decimal> ONB_AS_300_KG_2 { get; set; }
        public Nullable<decimal> ONB_PLUS_300_KG_2 { get; set; }
        public Nullable<decimal> ONB_AS_500_KG_2 { get; set; }
        public Nullable<decimal> ONB_PLUS_500_KG_2 { get; set; }
        public Nullable<decimal> ONB_EUR_BLD_QUANTITY_2 { get; set; }
        public Nullable<decimal> ONB_EUR_DANGER_PRO_COST_2 { get; set; }
        public Nullable<decimal> ONB_EUR_FIN_DANGER_PRO_COST_2 { get; set; }
        public Nullable<decimal> ONB_USA_BLD_QUANTITY_2 { get; set; }
        public Nullable<decimal> ONB_USA_DANGER_PRO_COST_2 { get; set; }
        public Nullable<decimal> ONB_USA_FIN_DANGER_PRO_COST_2 { get; set; }
        public string OVC_IMPORT_EXPORT_3 { get; set; }
        public Nullable<decimal> ONB_DISCOUNT_3 { get; set; }
        public Nullable<decimal> ONB_M_RATE_3 { get; set; }
        public Nullable<decimal> ONB_AS_N_RATE_3 { get; set; }
        public Nullable<decimal> ONB_N_RATE_3 { get; set; }
        public Nullable<decimal> ONB_AS_45_KG_3 { get; set; }
        public Nullable<decimal> ONB_PLUS_45_KG_3 { get; set; }
        public Nullable<decimal> ONB_AS_100_KG_3 { get; set; }
        public Nullable<decimal> ONB_PLUS_100_KG_3 { get; set; }
        public Nullable<decimal> ONB_AS_300_KG_3 { get; set; }
        public Nullable<decimal> ONB_PLUS_300_KG_3 { get; set; }
        public Nullable<decimal> ONB_AS_500_KG_3 { get; set; }
        public Nullable<decimal> ONB_PLUS_500_KG_3 { get; set; }
        public string OVC_REMARK { get; set; }
    }
}
