//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_EDF_DETAIL_MRPLOG
    {
        public string LOG_LOGIN_ID { get; set; }
        public System.DateTime LOG_TIME { get; set; }
        public string LOG_EVENT { get; set; }
        public string OVC_EDF_NO { get; set; }
        public decimal OVC_EDF_ITEM_NO { get; set; }
        public string OVC_CHI_NAME { get; set; }
        public string OVC_ENG_NAME { get; set; }
        public string OVC_BOX_NO { get; set; }
        public string OVC_ITEM_NO { get; set; }
        public string OVC_ITEM_NO2 { get; set; }
        public string OVC_ITEM_NO3 { get; set; }
        public Nullable<decimal> ONB_ITEM_COUNT { get; set; }
        public string OVC_ITEM_COUNT_UNIT { get; set; }
        public Nullable<decimal> ONB_WEIGHT { get; set; }
        public string OVC_WEIGHT_UNIT { get; set; }
        public Nullable<decimal> ONB_VOLUME { get; set; }
        public string OVC_VOLUME_UNIT { get; set; }
        public Nullable<decimal> ONB_LENGTH { get; set; }
        public Nullable<decimal> ONB_WIDTH { get; set; }
        public Nullable<decimal> ONB_HEIGHT { get; set; }
        public Nullable<decimal> ONB_MONEY { get; set; }
        public string OVC_CURRENCY { get; set; }
        public System.DateTime ODT_MODIFY_DATE { get; set; }
        public string OVC_CREATE_LOGIN_ID { get; set; }
        public string DIFF_USED { get; set; }
        public string DIFF_YYYYMM { get; set; }
        public System.Guid EDF_DET_MRP_SN { get; set; }
    }
}
