//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MTSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMT_SEA_TRANSPORT
    {
        public System.Guid ST_SN { get; set; }
        public System.Guid CO_SN { get; set; }
        public string OVC_START_PORT { get; set; }
        public string ONB_CARRIAGE_CURRENCY { get; set; }
        public string OVC_ROUTE { get; set; }
        public Nullable<System.DateTime> ODT_START_DATE { get; set; }
        public Nullable<System.DateTime> ODT_END_DATE { get; set; }
        public string OVC_IMPORT_EXPORT_1 { get; set; }
        public Nullable<decimal> ONB_DISCOUNT_1 { get; set; }
        public string OVC_ITEM_CATEGORY_1 { get; set; }
        public Nullable<decimal> ONB_LOWEST_FREIGHT_1 { get; set; }
        public string OVC_ITEM_CHI_NAME_1 { get; set; }
        public string OVC_ITEM_ENG_NAME_1 { get; set; }
        public Nullable<decimal> ONB_WEIGHT_PRICE_1 { get; set; }
        public Nullable<decimal> ONB_VOLUME_PRICE_1 { get; set; }
        public string OVC_IMPORT_EXPORT_2 { get; set; }
        public Nullable<decimal> ONB_DISCOUNT_2 { get; set; }
        public string OVC_ITEM_CATEGORY_2 { get; set; }
        public Nullable<decimal> ONB_LOWEST_FREIGHT_2 { get; set; }
        public string OVC_ITEM_CHI_NAME_2 { get; set; }
        public string OVC_ITEM_ENG_NAME_2 { get; set; }
        public Nullable<decimal> ONB_WEIGHT_PRICE_2 { get; set; }
        public Nullable<decimal> ONB_VOLUME_PRICE_2 { get; set; }
    }
}
