//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string USER_ID { get; set; }
        public string PWD { get; set; }
        public string USER_NAME { get; set; }
        public string DEPT_SN { get; set; }
        public string IUSER_PHONE { get; set; }
        public string CHANGE_DATE { get; set; }
        public string EMAIL_ACCOUNT { get; set; }
        public string PURCHASE_1 { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public System.Guid AC_SN { get; set; }
        public string AC_ID { get; set; }
        public Nullable<System.Guid> C_SN_TITLE { get; set; }
        public Nullable<System.Guid> AUTH_DEPT_SN { get; set; }
        public Nullable<decimal> ACCOUNT_STATUS { get; set; }
        public Nullable<decimal> ERROR_CNT { get; set; }
    }
}
