//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_SHIFT
    {
        public System.Guid AS_SN { get; set; }
        public string AACOUNT_ID { get; set; }
        public string AACOUNT_ID_ORI { get; set; }
        public string DEPT_ID { get; set; }
        public Nullable<System.DateTime> START_SATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
    }
}
