//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLSYS_LOG
    {
        public string AS_USER_ID { get; set; }
        public Nullable<System.DateTime> AS_DATE { get; set; }
        public string AS_IP { get; set; }
        public string AS_COMMAND { get; set; }
        public string AS_PAGE { get; set; }
        public string AS_ACT { get; set; }
        public System.Guid AS_SN { get; set; }
    }
}
