//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_PAGES
    {
        public string M_SN { get; set; }
        public string M_SN_PAR { get; set; }
        public string M_NAME { get; set; }
        public string M_URL { get; set; }
        public Nullable<decimal> M_ORD { get; set; }
        public string M_MODEL { get; set; }
        public string M_VISIBLE { get; set; }
    }
}
