//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROBLEM_DATA
    {
        public System.Guid PRO_SN { get; set; }
        public string PROSYS_SN { get; set; }
        public string PRO_ID { get; set; }
        public string PRO_DESC { get; set; }
        public string PRO_SOL_DESC { get; set; }
        public Nullable<System.Guid> PROKIND_SN { get; set; }
        public string PRO_STATUS { get; set; }
        public string PRO_SOL_PERSON { get; set; }
        public string PRO_REMARK { get; set; }
        public Nullable<bool> PRO_ADDFILE { get; set; }
        public Nullable<System.Guid> PROADD_SN { get; set; }
        public Nullable<System.Guid> OVC_CHECK_ID { get; set; }
        public Nullable<bool> OVC_CHECK_STATUS { get; set; }
        public Nullable<System.Guid> OVC_CONFIRM_ID { get; set; }
        public Nullable<bool> OVC_CONFIRM_STATUS { get; set; }
        public Nullable<System.DateTime> ODT_CREATE_DATE { get; set; }
        public string OVC_CREATE_ID { get; set; }
        public Nullable<System.DateTime> ODT_GET_DATE { get; set; }
        public Nullable<System.DateTime> ODT_PLAN_DATE { get; set; }
        public Nullable<System.DateTime> OVC_ACT_DATE { get; set; }
        public Nullable<System.DateTime> ODT_MODIFY_DATE { get; set; }
        public string OVC_MODIFY_LOGIN_ID { get; set; }
    }
}
