//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM1301
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_KIND { get; set; }
        public string OVC_LAB { get; set; }
        public string OVC_PUR_ASS_VEN_CODE { get; set; }
        public string OVC_BID_TIMES { get; set; }
        public string OVC_BID { get; set; }
        public string OVC_PUR_NSECTION { get; set; }
        public string OVC_PUR_SECTION { get; set; }
        public string OVC_PROPOSE { get; set; }
        public string OVC_DPROPOSE { get; set; }
        public string OVC_PUR_APPROVE { get; set; }
        public string OVC_PUR_DAPPROVE { get; set; }
        public string OVC_PUR_IPURCH { get; set; }
        public string OVC_PUR_IPURCH_ENG { get; set; }
        public string OVC_PUR_USER { get; set; }
        public string OVC_USER_TITLE { get; set; }
        public string OVC_KEYIN { get; set; }
        public string OVC_PUR_IUSER_PHONE { get; set; }
        public string OVC_PUR_IUSER_PHONE_EXT { get; set; }
        public string OVC_PUR_IUSER_PHONE_EXT1 { get; set; }
        public string OVC_USER_CELLPHONE { get; set; }
        public string OVC_PUR_AGENCY { get; set; }
        public string OVC_EST_REAR { get; set; }
        public string OVC_PUR_NPURCH { get; set; }
        public string OVC_TARGET_DO { get; set; }
        public string OVC_PUR_CURRENT { get; set; }
        public Nullable<decimal> ONB_PUR_RATE { get; set; }
        public Nullable<decimal> ONB_PUR_BUDGET { get; set; }
        public string OVC_AGNT_IN { get; set; }
        public string OVC_PUR_FEE_OK { get; set; }
        public string OVC_PUR_GOOD_OK { get; set; }
        public string OVC_PUR_TAX_OK { get; set; }
        public string OVC_PUR_DCANPO { get; set; }
        public string OVC_PUR_DCANRE { get; set; }
        public string OVC_EXAMPLE_SUPPORT { get; set; }
        public string OVC_PUR_ALLOW { get; set; }
        public string OVC_PUR_CREAT { get; set; }
        public string OVC_DOING_UNIT { get; set; }
        public string OVC_PERMISSION_UPDATE { get; set; }
        public string OVC_SUPERIOR_UNIT { get; set; }
        public string OVC_SECTION_CHIEF { get; set; }
        public string OVC_SHIP_TIMES { get; set; }
        public string OVC_RECEIVE_PLACE { get; set; }
        public string OVC_POI_IINSPECT { get; set; }
        public string OVC_COUNTRY { get; set; }
        public string OVC_WAY_TRANS { get; set; }
        public string OVC_RECEIVE_NSECTION { get; set; }
        public string OVC_FROM_TO { get; set; }
        public string OVC_TO_PLACE { get; set; }
        public string OVC_VERSION { get; set; }
        public Nullable<decimal> ONB_PUR_BUDGET_NT { get; set; }
        public Nullable<decimal> ONB_RESERVE_AMOUNT { get; set; }
        public string OVC_SPECIAL { get; set; }
        public string OVC_BID_MONEY { get; set; }
        public string OVC_NEGOTIATION { get; set; }
        public string OVC_QUOTE { get; set; }
        public string OVC_PLAN_PURCH { get; set; }
        public string OVC_COPY_FROM { get; set; }
        public string IS_PLURAL_BASIS { get; set; }
        public string IS_OPEN_CONTRACT { get; set; }
        public string IS_JUXTAPOSED_MANUFACTURER { get; set; }
    }
}
