//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM1301_PLAN
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PUR_AGENCY { get; set; }
        public string OVC_PUR_IPURCH { get; set; }
        public Nullable<decimal> ONB_PUR_BUDGET { get; set; }
        public string OVC_DAPPLY { get; set; }
        public string OVC_PUR_SECTION { get; set; }
        public string OVC_PUR_NSECTION { get; set; }
        public string OVC_PUR_USER { get; set; }
        public string OVC_KEYIN { get; set; }
        public string OVC_PUR_IUSER_PHONE { get; set; }
        public string OVC_PUR_IUSER_FAX { get; set; }
        public string OVC_PUR_IUSER_PHONE_EXT { get; set; }
        public string OVC_PUR_IUSER_PHONE_EXT1 { get; set; }
        public string OVC_USER_CELLPHONE { get; set; }
        public string EMAIL_ACCOUNT { get; set; }
        public string OVC_PUR_ASS_VEN_CODE { get; set; }
        public string OVC_LAB { get; set; }
        public string OVC_PLAN_PURCH { get; set; }
        public string OVC_PUR_APPROVE_DEP { get; set; }
        public string OVC_PUR_PROJE { get; set; }
        public Nullable<short> ONB_REVIEW_DAYS { get; set; }
        public Nullable<short> ONB_DELIVER_DAYS { get; set; }
        public Nullable<short> ONB_TENDER_DAYS { get; set; }
        public Nullable<short> ONB_RECEIVE_DAYS { get; set; }
        public string OVC_DAUDIT { get; set; }
        public string OVC_AUDITOR { get; set; }
        public string OVC_PUR_CREAT { get; set; }
        public string OVC_PURCH_OK { get; set; }
        public string OVC_DCANCEL { get; set; }
        public string OVC_CANCEL_REASON { get; set; }
        public string OVC_TENDER_DAYS { get; set; }
        public string OVC_RECEIVE_DAYS { get; set; }
        public string OVC_AUDIT_UNIT { get; set; }
        public string OVC_PURCHASE_UNIT { get; set; }
        public string OVC_CONTRACT_UNIT { get; set; }
        public string OVC_AGENT_UNIT { get; set; }
        public string OVC_FAC_CHECK { get; set; }
        public string OVC_OPEN_CHECK { get; set; }
        public string OVC_ON_SCHEDULE { get; set; }
        public string OVC_PURCH_MILITARY { get; set; }
        public string OVC_MILITARY_TYPE { get; set; }
    }
}
