//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM2133
    {
        public string CLASS { get; set; }
        public string ITEM { get; set; }
        public string CAL { get; set; }
        public string STEP { get; set; }
        public string FCODE { get; set; }
        public string NAME { get; set; }
        public string UNIT { get; set; }
        public string UI { get; set; }
        public string MATERIAL { get; set; }
        public string USEYEAR { get; set; }
        public string MEMO { get; set; }
        public bool LEVEL_SETP { get; set; }
        public string REL_CODE { get; set; }
    }
}
