//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMDEPT
    {
        public string OVC_DEPT_CDE { get; set; }
        public string OVC_ONNAME { get; set; }
        public string OVC_DEPT_FAX { get; set; }
        public string OVC_DEPT_MAILADDR { get; set; }
        public string OVC_DEPT_DOC_NAME { get; set; }
        public string OVC_MANAGER { get; set; }
        public string OVC_PURCHASE_DEPT { get; set; }
        public string OVC_MANAGER_TITLE { get; set; }
        public string OVC_EMAILADDRESS { get; set; }
        public string OVC_DEPT_SEC_NAME { get; set; }
        public string OVC_TOP_DEPT { get; set; }
        public string OVC_CLASS { get; set; }
        public string OVC_PURCHASE_OK { get; set; }
        public string OVC_DEPT_PHONE { get; set; }
        public string OVC_ENABLE { get; set; }
        public string OVC_CLASS2 { get; set; }
        public string OVC_TOP_DEPT2 { get; set; }
    }
}
