//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMSTANDARDITEM
    {
        public byte OVC_SYSTEM { get; set; }
        public string OVC_PUR_AGENCY { get; set; }
        public string OVC_IKIND { get; set; }
        public byte OVC_PURCH_KIND { get; set; }
        public short OVC_NO { get; set; }
        public string OVC_MEMO { get; set; }
        public string OVC_DESC { get; set; }
        public string OVC_CHECK { get; set; }
    }
}
