//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.GMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_LOGIN
    {
        public System.Guid AC_SN { get; set; }
        public string AC_ID { get; set; }
        public Nullable<System.DateTime> LOGIN_TIME { get; set; }
        public Nullable<System.DateTime> LOGOUT_TIME { get; set; }
        public string IP_ADDRESS { get; set; }
        public string IS_SUCCESS { get; set; }
        public Nullable<decimal> FAILURE_TIMES { get; set; }
    }
}
