//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using FCFDFE.Entity.GMModel;

    public partial class MPMSEntities : DbContext
    {
        public MPMSEntities()
            : base("name=MPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<TBM1114> TBM1114 { get; set; }
        public virtual DbSet<TBM1231_PLAN> TBM1231_PLAN { get; set; }
        public virtual DbSet<TBM1301D> TBM1301D { get; set; }
        public virtual DbSet<TBM5200_PPP> TBM5200_PPP { get; set; }
        public virtual DbSet<TBMPURCH_EXT> TBMPURCH_EXT { get; set; }
        public virtual DbSet<TBMRECEIVE_BID> TBMRECEIVE_BID { get; set; }
        public virtual DbSet<TBMRECEIVE_WORK> TBMRECEIVE_WORK { get; set; }
        public virtual DbSet<TBM1201> TBM1201 { get; set; }
        public virtual DbSet<TBM1302> TBM1302 { get; set; }
        public virtual DbSet<TBM1203> TBM1203 { get; set; }
        public virtual DbSet<TBM1303> TBM1303 { get; set; }
        public virtual DbSet<TBM1118> TBM1118 { get; set; }
        public virtual DbSet<TBM1118_1> TBM1118_1 { get; set; }
        public virtual DbSet<TBM1118_2> TBM1118_2 { get; set; }
        public virtual DbSet<TBM1118_3> TBM1118_3 { get; set; }
        public virtual DbSet<TBM1220_1> TBM1220_1 { get; set; }
        public virtual DbSet<TBM1231> TBM1231 { get; set; }
        public virtual DbSet<TBM1233> TBM1233 { get; set; }
        public virtual DbSet<TBM1202_COMMENT> TBM1202_COMMENT { get; set; }
        public virtual DbSet<TBMRECEIVE_BID_LOG> TBMRECEIVE_BID_LOG { get; set; }
        public virtual DbSet<TBMSTATUS> TBMSTATUS { get; set; }
        public virtual DbSet<TBM1202_1> TBM1202_1 { get; set; }
        public virtual DbSet<TBMOPINION> TBMOPINION { get; set; }
        public virtual DbSet<TBMOPINION_DETAIL> TBMOPINION_DETAIL { get; set; }
        public virtual DbSet<TBMOPINION_ITEM> TBMOPINION_ITEM { get; set; }
        public virtual DbSet<TBMRECEIVE_CONTRACT> TBMRECEIVE_CONTRACT { get; set; }
        public virtual DbSet<TBMBID_RESULT> TBMBID_RESULT { get; set; }
        public virtual DbSet<TBM1119> TBM1119 { get; set; }
        public virtual DbSet<TBMOVERSEE_LOG> TBMOVERSEE_LOG { get; set; }
        public virtual DbSet<TBM1118_HISTORY> TBM1118_HISTORY { get; set; }
        public virtual DbSet<TBM1119_HISTORY> TBM1119_HISTORY { get; set; }
        public virtual DbSet<TBM1201_HISTORY> TBM1201_HISTORY { get; set; }
        public virtual DbSet<TBM1220_1_HISTORY> TBM1220_1_HISTORY { get; set; }
        public virtual DbSet<TBM1301_HISTORY> TBM1301_HISTORY { get; set; }
        public virtual DbSet<TBMDOCCONTENT> TBMDOCCONTENT { get; set; }
        public virtual DbSet<TBMDOCLAW> TBMDOCLAW { get; set; }
        public virtual DbSet<TBMDOCPURCH> TBMDOCPURCH { get; set; }
        public virtual DbSet<TBMMESSAGE> TBMMESSAGE { get; set; }
        public virtual DbSet<TBM1202_2> TBM1202_2 { get; set; }
        public virtual DbSet<TBM1202_ADVICE> TBM1202_ADVICE { get; set; }
        public virtual DbSet<TBM1313> TBM1313 { get; set; }
        public virtual DbSet<TBMDOCTYPE> TBMDOCTYPE { get; set; }
        public virtual DbSet<TBMPAY_MONEY> TBMPAY_MONEY { get; set; }
        public virtual DbSet<TBM5200_1> TBM5200_1 { get; set; }
        public virtual DbSet<VIDELIVERY> VIDELIVERY { get; set; }
        public virtual DbSet<TBMDELIVERY> TBMDELIVERY { get; set; }
        public virtual DbSet<TBM1314> TBM1314 { get; set; }
        public virtual DbSet<TBM1313_ITEM> TBM1313_ITEM { get; set; }
        public virtual DbSet<TBMRECEIVE_CHECK> TBMRECEIVE_CHECK { get; set; }
        public virtual DbSet<TBMRECEIVE_CHECK_ITEM> TBMRECEIVE_CHECK_ITEM { get; set; }
        public virtual DbSet<TBMAPPLY_INSPECT> TBMAPPLY_INSPECT { get; set; }
        public virtual DbSet<TBMAUDIT> TBMAUDIT { get; set; }
        public virtual DbSet<TBMAUDIT_INSPECT> TBMAUDIT_INSPECT { get; set; }
        public virtual DbSet<TBMGRANTED> TBMGRANTED { get; set; }
        public virtual DbSet<TBMMANAGE_CASH> TBMMANAGE_CASH { get; set; }
        public virtual DbSet<TBMMANAGE_PROM> TBMMANAGE_PROM { get; set; }
        public virtual DbSet<TBMMANAGE_STOCK> TBMMANAGE_STOCK { get; set; }
        public virtual DbSet<TBMRECEIVE_INSPECT> TBMRECEIVE_INSPECT { get; set; }
        public virtual DbSet<TBM1119_1> TBM1119_1 { get; set; }
        public virtual DbSet<TBM1202_3> TBM1202_3 { get; set; }
        public virtual DbSet<TBM1202_4> TBM1202_4 { get; set; }
        public virtual DbSet<TBM1202_5> TBM1202_5 { get; set; }
        public virtual DbSet<TBM1202_6> TBM1202_6 { get; set; }
        public virtual DbSet<TBM1202_7> TBM1202_7 { get; set; }
        public virtual DbSet<TBM1202_8> TBM1202_8 { get; set; }
        public virtual DbSet<TBM1202_9> TBM1202_9 { get; set; }
        public virtual DbSet<TBM1301_RECORD> TBM1301_RECORD { get; set; }
        public virtual DbSet<TBM1302_ITEM> TBM1302_ITEM { get; set; }
        public virtual DbSet<TBMANNOUNCE_MODIFY> TBMANNOUNCE_MODIFY { get; set; }
        public virtual DbSet<TBMANNOUNCE_OPEN> TBMANNOUNCE_OPEN { get; set; }
        public virtual DbSet<TBMANNOUNCE_VENDOR> TBMANNOUNCE_VENDOR { get; set; }
        public virtual DbSet<TBMBID_DOC> TBMBID_DOC { get; set; }
        public virtual DbSet<TBMBID_DOC_ITEM> TBMBID_DOC_ITEM { get; set; }
        public virtual DbSet<TBMCONTRACT_MAKE> TBMCONTRACT_MAKE { get; set; }
        public virtual DbSet<TBMCONTRACT_MAKE_ITEM> TBMCONTRACT_MAKE_ITEM { get; set; }
        public virtual DbSet<TBMCONTRACT_MODIFY> TBMCONTRACT_MODIFY { get; set; }
        public virtual DbSet<TBMCONTRACT_MODIFY_ITEM> TBMCONTRACT_MODIFY_ITEM { get; set; }
        public virtual DbSet<TBMCONTRACT_NOTICE> TBMCONTRACT_NOTICE { get; set; }
        public virtual DbSet<TBMFAC_STATUS> TBMFAC_STATUS { get; set; }
        public virtual DbSet<TBMFREEDUTY> TBMFREEDUTY { get; set; }
        public virtual DbSet<TBMFREEDUTY_ITEM> TBMFREEDUTY_ITEM { get; set; }
        public virtual DbSet<TBMINSPECT_RECORD> TBMINSPECT_RECORD { get; set; }
        public virtual DbSet<TBMINSPECT_REPORT> TBMINSPECT_REPORT { get; set; }
        public virtual DbSet<TBMINSPECT_REPORT_ITEM> TBMINSPECT_REPORT_ITEM { get; set; }
        public virtual DbSet<TBMRECEIVE_ANNOUNCE> TBMRECEIVE_ANNOUNCE { get; set; }
        public virtual DbSet<TBMRECEIVE_ANNOUNCE_ENG> TBMRECEIVE_ANNOUNCE_ENG { get; set; }
        public virtual DbSet<TBMRECEIVE_ANNOUNCE_EXT> TBMRECEIVE_ANNOUNCE_EXT { get; set; }
        public virtual DbSet<TBMRECEIVE_BID_ITEM> TBMRECEIVE_BID_ITEM { get; set; }
        public virtual DbSet<TBMRECEIVE_LOG> TBMRECEIVE_LOG { get; set; }
        public virtual DbSet<TBMRESULT_ANNOUNCE> TBMRESULT_ANNOUNCE { get; set; }
        public virtual DbSet<TBMRESULT_ANNOUNCE_NONE> TBMRESULT_ANNOUNCE_NONE { get; set; }
        public virtual DbSet<TBMRESULT_NOTICE> TBMRESULT_NOTICE { get; set; }
        public virtual DbSet<TBMBID_BACK> TBMBID_BACK { get; set; }
        public virtual DbSet<TBMBID_BACK_ITEM> TBMBID_BACK_ITEM { get; set; }
        public virtual DbSet<TBMBID_DOC_LOG> TBMBID_DOC_LOG { get; set; }
        public virtual DbSet<TBMBID_END> TBMBID_END { get; set; }
        public virtual DbSet<TBMBID_VENDOR> TBMBID_VENDOR { get; set; }
        public virtual DbSet<TBMDEPT_EXT> TBMDEPT_EXT { get; set; }
        public virtual DbSet<TBMDELIVERY_ITEM> TBMDELIVERY_ITEM { get; set; }
        public virtual DbSet<TBM1202_RESULT> TBM1202_RESULT { get; set; }
        public virtual DbSet<VITBM1302> VITBM1302 { get; set; }
        public virtual DbSet<VIWORKSTATUS21> VIWORKSTATUS21 { get; set; }
        public virtual DbSet<TBM1231_HISTORY> TBM1231_HISTORY { get; set; }
        public virtual DbSet<TBM1202> TBM1202 { get; set; }
    
        public virtual int PG_CHANGE_PURCH_ID(string xOVC_PURCH, string xNEW_PURCH, string xOVC_USER, ObjectParameter rTN_MSG)
        {

            var xOVC_PURCHParameter = (xOVC_PURCH != null) ? 
                new ObjectParameter("XOVC_PURCH", xOVC_PURCH) :
                new ObjectParameter("XOVC_PURCH", typeof(string));
    
            var xNEW_PURCHParameter = (xNEW_PURCH != null) ?  
                new ObjectParameter("XNEW_PURCH", xNEW_PURCH) :
                new ObjectParameter("XNEW_PURCH", typeof(string));

            var xOVC_USERParameter = (xOVC_USER != null) ?    
                new ObjectParameter("XOVC_USER", xOVC_USER) :
                new ObjectParameter("XOVC_USER", typeof(string));

            //((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MPMSEntities.PROCEDURE1",xOVC_PURCHParameter,xOVC_USERParameter);
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MPMSEntities.PG_CHANGE_PURCH_ID", xOVC_PURCHParameter, xNEW_PURCHParameter, xOVC_USERParameter, rTN_MSG);
            //return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MPMSEntities.PG_CHANGE_PURCH_ID", xOVC_PURCHParameter, xNEW_PURCHParameter, xOVC_USERParameter);//, rTN_MSG);

        }
    
        public virtual int PG_TBM1301_CANCEL_OLTP(string xOVC_PURCH, string xOVC_PUR_DCANPO, string xOVC_PUR_DCANRE, ObjectParameter rTN_MSG)
        {
            var xOVC_PURCHParameter = xOVC_PURCH != null ?
                new ObjectParameter("XOVC_PURCH", xOVC_PURCH) :
                new ObjectParameter("XOVC_PURCH", typeof(string));
    
            var xOVC_PUR_DCANPOParameter = xOVC_PUR_DCANPO != null ?
                new ObjectParameter("XOVC_PUR_DCANPO", xOVC_PUR_DCANPO) :
                new ObjectParameter("XOVC_PUR_DCANPO", typeof(string));
    
            var xOVC_PUR_DCANREParameter = xOVC_PUR_DCANRE != null ?
                new ObjectParameter("XOVC_PUR_DCANRE", xOVC_PUR_DCANRE) :
                new ObjectParameter("XOVC_PUR_DCANRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MPMSEntities.PG_TBM1301_CANCEL_OLTP", xOVC_PURCHParameter, xOVC_PUR_DCANPOParameter, xOVC_PUR_DCANREParameter, rTN_MSG);
        }
        //GMModel CIMS E 模組 

        public virtual DbSet<ACCOUNT_AUTH> ACCOUNT_AUTH { get; set; }
        public virtual DbSet<TBM1301> TBM1301 { get; set; }
        public virtual DbSet<TBM1407> TBM1407 { get; set; }
        public virtual DbSet<TBMDEPT> TBMDEPTs { get; set; }
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<TBM1301_PLAN> TBM1301_PLAN { get; set; }
        public virtual DbSet<TBM1220_2> TBM1220_2 { get; set; }
    }
}
