//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM1201_HISTORY
    {
        public string OVC_PURCH { get; set; }
        public short ONB_POI_ICOUNT { get; set; }
        public string OVC_POI_NSTUFF_CHN { get; set; }
        public string OVC_POI_NSTUFF_ENG { get; set; }
        public string NSN_KIND { get; set; }
        public string NSN { get; set; }
        public string OVC_BRAND { get; set; }
        public string OVC_MODEL { get; set; }
        public string OVC_POI_IREF { get; set; }
        public string OVC_FCODE { get; set; }
        public string OVC_POI_IUNIT { get; set; }
        public Nullable<decimal> ONB_POI_QORDER_PLAN { get; set; }
        public Nullable<decimal> ONB_POI_QORDER_CONT { get; set; }
        public Nullable<decimal> ONB_POI_MPRICE_PLAN { get; set; }
        public Nullable<decimal> ONB_POI_MPRICE_CONT { get; set; }
        public string OVC_FIRST_BUY { get; set; }
        public string OVC_POI_IPURCH_BEF { get; set; }
        public string OVC_CURR_MPRICE_BEF { get; set; }
        public Nullable<decimal> ONB_POI_QORDER_BEF { get; set; }
        public Nullable<decimal> ONB_POI_MPRICE_BEF { get; set; }
        public string OVC_POI_NDESC { get; set; }
        public string OVC_SAME_QUALITY { get; set; }
        public string OVC_VERSION { get; set; }
    }
}
