//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM1202_8
    {
        public string OVC_PURCH { get; set; }
        public string OVC_CHECK_UNIT { get; set; }
        public byte ONB_CHECK_TIMES { get; set; }
        public string OVC_IKIND { get; set; }
        public byte ONB_NO { get; set; }
        public string OVC_CHECK { get; set; }
        public string OVC_MEMO { get; set; }
        public string OVC_PERFORM { get; set; }
        public string OVC_STANDARD { get; set; }
        public string OVC_ORG { get; set; }
    }
}
