//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM1303
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_DOPEN { get; set; }
        public string OVC_OPEN_HOUR { get; set; }
        public string OVC_OPEN_MIN { get; set; }
        public Nullable<short> ONB_TIMES { get; set; }
        public string OVC_PLACE { get; set; }
        public string OVC_ROOM { get; set; }
        public string OVC_OPEN_METHOD { get; set; }
        public string OVC_BID_METHOD { get; set; }
        public string OVC_METHOD_1 { get; set; }
        public string OVC_METHOD_2 { get; set; }
        public string OVC_METHOD_3 { get; set; }
        public string OVC_22_1_NO { get; set; }
        public string OVC_RESTRICT_1 { get; set; }
        public string OVC_RESTRICT_2 { get; set; }
        public Nullable<short> ONB_BID_VENDORS { get; set; }
        public string OVC_CHECK_RESULT_1 { get; set; }
        public string OVC_CHECK_RESULT_2 { get; set; }
        public Nullable<short> ONB_OK_VENDORS { get; set; }
        public Nullable<short> ONB_NOTOK_VENDORS { get; set; }
        public string OVC_VENDORS_NAME { get; set; }
        public string OVC_AUDIT_SPEC { get; set; }
        public string OVC_AUDIT_DOC { get; set; }
        public string OVC_AUDIT_OTHER { get; set; }
        public Nullable<short> ONB_AUDIT_DOC { get; set; }
        public string OVC_CHECK_DOC { get; set; }
        public Nullable<short> ONB_OK_EFFECT { get; set; }
        public Nullable<short> ONB_NOTOK_EFFECT { get; set; }
        public string OVC_EFFECTS_NAME { get; set; }
        public Nullable<short> ONB_RESULT_OK { get; set; }
        public Nullable<short> ONB_RESULT_NOTOK { get; set; }
        public string OVC_RESULT { get; set; }
        public string OVC_RESULT_REASON { get; set; }
        public Nullable<short> ONB_BID_VENDOR_LAW { get; set; }
        public string OVC_BACK { get; set; }
        public string OVC_VEN_CST { get; set; }
        public string OVC_VEN_TITLE { get; set; }
        public string OVC_FOLLOW_OK { get; set; }
        public Nullable<decimal> ONB_BID_MONEY { get; set; }
        public string OVC_BID_CURRENT { get; set; }
        public Nullable<decimal> ONB_BID_BUDGET { get; set; }
        public string OVC_CURRENT { get; set; }
        public Nullable<decimal> ONB_COMMITTEE_BUDGET { get; set; }
        public string OVC_COMMITTEE_CURRENT { get; set; }
        public string OVC_LAW_ITEM { get; set; }
        public string OVC_LAW_NO { get; set; }
        public string OVC_NONE_BID_NO { get; set; }
        public string OVC_ADDITIONAL { get; set; }
        public string OVC_FINISH_1 { get; set; }
        public string OVC_FINISH_2 { get; set; }
        public string OVC_ADVICE { get; set; }
        public Nullable<decimal> ONB_BID_RESULT { get; set; }
        public string OVC_RESULT_CURRENT { get; set; }
        public Nullable<decimal> ONB_RESULT_RATE { get; set; }
        public string OVC_CHAIRMAN { get; set; }
        public string OVC_NAME { get; set; }
        public string OVC_DAPPROVE { get; set; }
        public string OVC_RESULT_DESC { get; set; }
        public short ONB_GROUP { get; set; }
    }
}
