//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM1203
    {
        public string OVC_VEN_CST { get; set; }
        public string OVC_VEN_ADDRESS { get; set; }
        public string OVC_VEN_ADDRESS_1 { get; set; }
        public string OVC_PUR_CREATE { get; set; }
        public string OVC_DRECOVERY { get; set; }
        public string OVC_PUR_TUPDATE { get; set; }
        public string OVC_IBUILD_UNIT { get; set; }
        public string OVC_ICOUNTRY { get; set; }
        public string OVC_VEN_TITLE { get; set; }
        public string OVC_NVEN { get; set; }
        public string CAGE { get; set; }
        public string OVC_FAX_NO { get; set; }
        public string OVC_VEN_ITEL { get; set; }
        public string OVC_IPURCHASE { get; set; }
        public Nullable<short> ONB_QSUBTRACT { get; set; }
        public string OVC_BOSS { get; set; }
        public string USERID { get; set; }
        public string CHECKED { get; set; }
        public string INPUT_USER { get; set; }
        public string OVC_MAIN_PRODUCT { get; set; }
        public string CSIST_VEN_CST { get; set; }
        public string OVC_STATUS { get; set; }
        public string GINGE_VEN_CST { get; set; }
        public string MIXED_CAGE { get; set; }
        public string MIXED_VEN_CST { get; set; }
        public string OVC_UPDATED { get; set; }
        public Nullable<decimal> KEY { get; set; }
        public string BID_PURCH { get; set; }
        public string CAGE_DATE { get; set; }
        public string PERFORM_NAME { get; set; }
        public string OVC_MANAGE { get; set; }
        public string OVC_DMANAGE_BEGIN { get; set; }
        public string OVC_DMANAGE_END { get; set; }
        public System.Guid OVC_VEN_SN { get; set; }
    }
}
