//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM1314
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_DOPEN { get; set; }
        public string OVC_VEN_CST { get; set; }
        public string OVC_VEN_TITLE { get; set; }
        public short ONB_GROUP { get; set; }
        public string OVC_OK_BID { get; set; }
        public string OVC_PUR_CURRENT { get; set; }
        public Nullable<decimal> ONB_PUR_RATE { get; set; }
        public Nullable<decimal> ONB_MBID { get; set; }
        public Nullable<decimal> ONB_MINIS_LOWEST { get; set; }
        public Nullable<decimal> ONB_MINIS_1 { get; set; }
        public Nullable<decimal> ONB_MINIS_2 { get; set; }
        public Nullable<decimal> ONB_MINIS_3 { get; set; }
        public Nullable<decimal> ONB_MINIS_4 { get; set; }
        public Nullable<decimal> ONB_MINIS_5 { get; set; }
        public Nullable<decimal> ONB_MINIS_6 { get; set; }
        public Nullable<decimal> ONB_MINIS_7 { get; set; }
        public Nullable<decimal> ONB_MINIS_8 { get; set; }
        public Nullable<decimal> ONB_MINIS_9 { get; set; }
        public Nullable<decimal> ONB_MINIS_10 { get; set; }
        public Nullable<decimal> ONB_MINIS_11 { get; set; }
        public Nullable<decimal> ONB_MINIS_12 { get; set; }
        public string OVC_MBID { get; set; }
        public string OVC_MINIS_LOWEST { get; set; }
        public string OVC_MINIS_1 { get; set; }
        public string OVC_MINIS_2 { get; set; }
        public string OVC_MINIS_3 { get; set; }
        public string OVC_MINIS_4 { get; set; }
        public string OVC_MINIS_5 { get; set; }
        public string OVC_MINIS_6 { get; set; }
        public string OVC_MINIS_7 { get; set; }
        public string OVC_MINIS_8 { get; set; }
        public string OVC_MINIS_9 { get; set; }
        public string OVC_MINIS_10 { get; set; }
        public string OVC_MINIS_11 { get; set; }
        public string OVC_MINIS_12 { get; set; }
        public string OVC_KMBID { get; set; }
        public string OVC_KMINIS_LOWEST { get; set; }
        public string OVC_KMINIS_1 { get; set; }
        public string OVC_KMINIS_2 { get; set; }
        public string OVC_KMINIS_3 { get; set; }
        public string OVC_KMINIS_4 { get; set; }
        public string OVC_KMINIS_5 { get; set; }
        public string OVC_KMINIS_6 { get; set; }
        public string OVC_KMINIS_7 { get; set; }
        public string OVC_KMINIS_8 { get; set; }
        public string OVC_KMINIS_9 { get; set; }
        public string OVC_KMINIS_10 { get; set; }
        public string OVC_KMINIS_11 { get; set; }
        public string OVC_KMINIS_12 { get; set; }
    }
}
