//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM1313_ITEM
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_DOPEN { get; set; }
        public string OVC_KIND { get; set; }
        public string OVC_VEN_TITLE { get; set; }
        public short ONB_ITEM { get; set; }
        public string OVC_ITEM_NAME { get; set; }
        public string OVC_ITEM_NAME_1 { get; set; }
        public string OVC_ITEM_NAME_2 { get; set; }
        public string OVC_ITEM_NAME_3 { get; set; }
        public string OVC_ITEM_NAME_4 { get; set; }
        public string OVC_ITEM_NAME_5 { get; set; }
        public string OVC_ITEM_NAME_6 { get; set; }
        public string OVC_ITEM_NAME_7 { get; set; }
        public string OVC_RESULT { get; set; }
        public string OVC_REJECT_REASON_1 { get; set; }
        public string OVC_REJECT_REASON_2 { get; set; }
        public string OVC_REJECT_REASON_3 { get; set; }
        public string OVC_REJECT_REASON_4 { get; set; }
        public Nullable<short> ONB_GROUP { get; set; }
        public System.Guid OVC_SN { get; set; }
    }
}
