//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM1231_PLAN
    {
        public string OVC_PURCH { get; set; }
        public string OVC_BUDGET_YEAR { get; set; }
        public string OVC_BUDGET_MONTH { get; set; }
        public string OVC_POI_IBDG { get; set; }
        public string OVC_IKIND { get; set; }
        public string OVC_PJNAME { get; set; }
        public Nullable<decimal> ONB_MONEY { get; set; }
        public System.Guid OVC_P_SN { get; set; }
    }
}
