//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM1118_HISTORY
    {
        public string OVC_PURCH { get; set; }
        public string OVC_ISOURCE { get; set; }
        public string OVC_POI_IBDG { get; set; }
        public string OVC_IKIND { get; set; }
        public string OVC_PJNAME { get; set; }
        public string OVC_YY { get; set; }
        public string OVC_MM { get; set; }
        public string OVC_CURRENT { get; set; }
        public Nullable<decimal> ONB_RATE { get; set; }
        public Nullable<decimal> ONB_MBUD { get; set; }
        public string OVC_VERSION { get; set; }
    }
}
