//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM5200_PPP
    {
        public string USER_ID { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_NAME { get; set; }
        public string OVC_PUR_SECTION { get; set; }
        public string OVC_PUR_IUSER_PHONE { get; set; }
        public string OVC_PRIV_LEVEL { get; set; }
        public string CHANGE_DATE { get; set; }
        public string EMAIL_ACCOUNT { get; set; }
        public string EMAIL_PASSWD { get; set; }
        public string ROLE_IKIND { get; set; }
        public string OVC_ENABLE { get; set; }
        public string OVC_PURCHASE_1 { get; set; }
        public Nullable<System.DateTime> OVC_LAST_LOGIN { get; set; }
    }
}
