//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMANNOUNCE_VENDOR
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public short ONB_GROUP { get; set; }
        public string OVC_VEN_CST { get; set; }
        public string OVC_VEN_TITLE { get; set; }
        public string OVC_VEN_TEL { get; set; }
        public string OVC_VEN_ADDRESS { get; set; }
        public string OVC_EMPLOYEE_OVER { get; set; }
        public Nullable<int> ONB_EMPLOYEES { get; set; }
        public Nullable<int> ONB_EMPLOYEES_SPECIAL { get; set; }
        public Nullable<int> ONB_EMPLOYEES_ABORIGINAL { get; set; }
        public string OVC_CONTRACT_START { get; set; }
        public string OVC_CONTRACT_END { get; set; }
        public string OVC_VEN_KIND { get; set; }
        public Nullable<decimal> ONB_BID_RESULT_MERG { get; set; }
        public string OVC_MIDDLE_SMALL { get; set; }
        public Nullable<decimal> ONB_BID_RESULT { get; set; }
        public Nullable<decimal> ONB_BID_JOB { get; set; }
        public string OVC_VEN_COUNTRY { get; set; }
        public string OVC_VEN_103_2 { get; set; }
    }
}
