//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMAPPLY_INSPECT
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_VEN_CST { get; set; }
        public short ONB_TIMES { get; set; }
        public short ONB_INSPECT_TIMES { get; set; }
        public short ONB_RE_INSPECT_TIMES { get; set; }
        public string OVC_INSPECT_UNIT { get; set; }
        public string OVC_DAPPLY { get; set; }
        public string OVC_IAPPLY { get; set; }
        public string OVC_INSPECTED_STUFF { get; set; }
        public Nullable<decimal> ONB_QUALITY { get; set; }
        public string OVC_INSPECT_DESC { get; set; }
        public string OVC_ATTACH { get; set; }
        public string OVC_TAKER { get; set; }
        public string OVC_MARK { get; set; }
        public string OVC_APPLY_DESC { get; set; }
        public Nullable<decimal> ONB_CASE_QUALITY { get; set; }
        public Nullable<short> ONB_REPORT_ORG { get; set; }
        public Nullable<short> ONB_REPORT_COPY { get; set; }
        public string OVC_DO_NAME { get; set; }
        public string OVC_BACK { get; set; }
        public string OVC_INSPECTED_STUFF_ENG { get; set; }
        public Nullable<short> ONB_REPORT { get; set; }
        public Nullable<short> ONB_REPORT_ENG { get; set; }
    }
}
