//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMAUDIT
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_VEN_CST { get; set; }
        public short ONB_TIMES { get; set; }
        public short ONB_AUDIT { get; set; }
        public string OVC_PERFORMANCE_LIMIT { get; set; }
        public string OVC_DAUDIT { get; set; }
        public string OVC_VEN_TITLE { get; set; }
        public string OVC_VEN_ADDRESS { get; set; }
        public string OVC_PERFORMANCE_PLACE { get; set; }
        public string OVC_DNOTICE { get; set; }
        public string OVC_INOTICE { get; set; }
        public string OVC_DESC { get; set; }
        public string OVC_DO_NAME { get; set; }
    }
}
