//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMANNOUNCE_MODIFY
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_DWORK { get; set; }
        public string OVC_AGNT_IN { get; set; }
        public string OVC_NAME { get; set; }
        public string OVC_TELEPHONE { get; set; }
        public string OVC_DESC_ORG { get; set; }
        public string OVC_DESC_MODIFY { get; set; }
        public string OVC_DOPEN_MODIFY { get; set; }
        public string OVC_DOPEN_N { get; set; }
        public string OVC_OPEN_HOUR_N { get; set; }
        public string OVC_OPEN_MIN_N { get; set; }
        public string OVC_DOPEN { get; set; }
        public string OVC_OPEN_HOUR { get; set; }
        public string OVC_OPEN_MIN { get; set; }
        public string OVC_DESC { get; set; }
        public string OVC_MEMO { get; set; }
        public string OVC_DANNOUNCE { get; set; }
        public string OVC_DAPPROVE { get; set; }
        public string OVC_DSEND { get; set; }
    }
}
