//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMCONTRACT_MODIFY_ITEM
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_VEN_CST { get; set; }
        public string OVC_KIND { get; set; }
        public short ONB_TIMES { get; set; }
        public short ONB_POI_ICOUNT { get; set; }
        public Nullable<decimal> ONB_QDELIVERY_BEF { get; set; }
        public Nullable<decimal> ONB_MDELIVERY_BEF { get; set; }
        public Nullable<decimal> ONB_QDELIVERY_AFT { get; set; }
        public Nullable<decimal> ONB_MDELIVERY_AFT { get; set; }
        public string OVC_BEFORE_MODIFY { get; set; }
        public string OVC_AFTER_MODIFY { get; set; }
    }
}
