//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMCONTRACT_NOTICE
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_NOTICE_TITLE { get; set; }
        public string OVC_NOTICE_TIME { get; set; }
        public string OVC_ATTACH_NAME { get; set; }
        public string OVC_NOTICE_KIND { get; set; }
        public string OVC_NAME { get; set; }
        public string OVC_MEMO { get; set; }
    }
}
