//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMDELIVERY
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_VEN_CST { get; set; }
        public short ONB_SHIP_TIMES { get; set; }
        public string OVC_DELIVERY_CONTRACT { get; set; }
        public Nullable<int> ONB_DAYS_CONTRACT { get; set; }
        public string OVC_DELIVERY { get; set; }
        public Nullable<decimal> ONB_MCONTRACT { get; set; }
        public Nullable<decimal> ONB_MDELIVERY { get; set; }
        public string OVC_DELIVERY_PLACE { get; set; }
        public Nullable<short> ONB_DINSPECT_SOP { get; set; }
        public string OVC_DAIRSHIP { get; set; }
        public string OVC_DAIRSHIP_PLAN { get; set; }
        public string OVC_DINFORM { get; set; }
        public string OVC_DINFORM_PLAN { get; set; }
        public string OVC_DJOINCHECK { get; set; }
        public string OVC_DJOINCHECK_PLAN { get; set; }
        public string OVC_DSHIPMENT { get; set; }
        public string OVC_DSHIPMENT_PLAN { get; set; }
        public string OVC_DINVENTORY { get; set; }
        public string OVC_DINVENTORY_PLAN { get; set; }
        public string OVC_DINSPECT { get; set; }
        public string OVC_DINSPECT_PLAN { get; set; }
        public string OVC_DPAY { get; set; }
        public string OVC_DELAY_REASON { get; set; }
        public string OVC_DO_NAME { get; set; }
        public string OVC_DINSPECT_SOP { get; set; }
        public string OVC_DPAY_PLAN { get; set; }
        public string OVC_ACCORDING { get; set; }
        public string OVC_DACCORDING { get; set; }
        public string OVC_ACCORDING_PLACE { get; set; }
        public string OVC_DELIVERY_PERIOD { get; set; }
    }
}
