//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMDOCCONTENT
    {
        public string DOC_TYPENO { get; set; }
        public string DOC_NO { get; set; }
        public string DOC_LAW_NO { get; set; }
        public string DOC_CON_NO { get; set; }
        public string DOC_CON { get; set; }
        public string DOC_CON_DESC { get; set; }
        public string DOC_CHECK { get; set; }
        public string DOC_COMMIT { get; set; }
    }
}
