//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMDEPT_EXT
    {
        public string OVC_DEPT_CDE { get; set; }
        public string ORG_ID { get; set; }
        public string DEPT_OID { get; set; }
        public string ORG_DEPT { get; set; }
        public string ORG_DEPT_NAME { get; set; }
        public string ORG_DEPT_ADDR_ZIP { get; set; }
        public string ORG_DEPT_ADDR_CITY { get; set; }
        public string ORG_DEPT_ADDR_AREA { get; set; }
        public string ORG_DEPT_ADDR { get; set; }
        public string OVC_TELEPHONE_AREA { get; set; }
        public string OVC_TELEPHONE { get; set; }
        public string OVC_TELEPHONE_EXT { get; set; }
        public string EMAIL { get; set; }
    }
}
