//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMFREEDUTY
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_VEN_CST { get; set; }
        public short ONB_TIMES { get; set; }
        public string OVC_DUTY_KIND { get; set; }
        public short ONB_NO { get; set; }
        public string OVC_TAX_STUFF { get; set; }
        public string OVC_GOOD_TOTAL { get; set; }
        public string OVC_GOOD_USE { get; set; }
        public string OVC_GOOD_IAPPROVE { get; set; }
        public string OVC_EXPORT_VENDOR { get; set; }
        public string OVC_TAX_COUNTRY { get; set; }
        public string OVC_TAX_QUALITY { get; set; }
        public string OVC_TAX_UNIT { get; set; }
        public string OVC_TAX_UNIT_SUM { get; set; }
        public string OVC_TAX_MODEL { get; set; }
        public string OVC_TAX_DESC { get; set; }
        public string OVC_UNIT_PRICE { get; set; }
        public string OVC_TAX_USE { get; set; }
        public string OVC_TAX_DIMPORT { get; set; }
        public string OVC_TAX_PLACE { get; set; }
        public string OVC_TAX_VENDOR { get; set; }
        public string OVC_GOOD_BUDGET { get; set; }
        public string OVC_GOOD_DESC { get; set; }
        public string OVC_GOOD_NAPPROVE { get; set; }
        public string OVC_GOOD_QUALITY { get; set; }
        public string OVC_GOOD_DAPPLY { get; set; }
        public string OVC_GOOD_IAPPLY { get; set; }
        public string OVC_GOOD_AUDIT { get; set; }
        public string OVC_GOOD_NSECTION { get; set; }
        public string OVC_APPLY { get; set; }
        public string OVC_APPROVE_DESC { get; set; }
        public string OVC_DO_NAME { get; set; }
    }
}
