//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMINSPECT_REPORT
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_VEN_CST { get; set; }
        public short ONB_TIMES { get; set; }
        public short ONB_INSPECT_TIMES { get; set; }
        public short ONB_RE_INSPECT_TIMES { get; set; }
        public string OVC_KIND { get; set; }
        public string OVC_REPORT_DESC { get; set; }
        public string OVC_DINSPECT { get; set; }
        public string OVC_RESULT_1 { get; set; }
        public string OVC_RESULT_2 { get; set; }
        public string OVC_RESULT_2_PERCENT { get; set; }
        public string OVC_RESULT_3 { get; set; }
        public string OVC_RESULT_4 { get; set; }
        public string OVC_RESULT_4_DELAY { get; set; }
        public string OVC_RESULT_4_PUNISH { get; set; }
        public string OVC_DO_NAME { get; set; }
        public string OVC_RESULT_5 { get; set; }
    }
}
