//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMMANAGE_CASH
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_OWN_NO { get; set; }
        public string OVC_WORK_NO { get; set; }
        public string OVC_OWN_NAME { get; set; }
        public string OVC_OWN_ADDRESS { get; set; }
        public string OVC_OWN_TEL { get; set; }
        public Nullable<decimal> ONB_ALL_MONEY { get; set; }
        public string OVC_MARK { get; set; }
        public string OVC_WORK_NAME { get; set; }
        public string OVC_WORK_UNIT { get; set; }
        public string OVC_RECEIVE_NO { get; set; }
        public string OVC_DRECEIVE { get; set; }
        public string OVC_BACK_NO { get; set; }
        public string OVC_DBACK { get; set; }
        public string OVC_BACK_REASON { get; set; }
        public string OVC_BACK_MARK { get; set; }
        public Nullable<byte> ONB_ITEM_1 { get; set; }
        public string OVC_REASON_1 { get; set; }
        public string OVC_CURRENT_1 { get; set; }
        public Nullable<decimal> ONB_MONEY_1 { get; set; }
        public Nullable<decimal> ONB_MONEY_NT_1 { get; set; }
        public Nullable<byte> ONB_ITEM_2 { get; set; }
        public string OVC_REASON_2 { get; set; }
        public string OVC_CURRENT_2 { get; set; }
        public Nullable<decimal> ONB_MONEY_2 { get; set; }
        public Nullable<decimal> ONB_MONEY_NT_2 { get; set; }
        public Nullable<byte> ONB_ITEM_3 { get; set; }
        public string OVC_REASON_3 { get; set; }
        public string OVC_CURRENT_3 { get; set; }
        public Nullable<decimal> ONB_MONEY_3 { get; set; }
        public Nullable<decimal> ONB_MONEY_NT_3 { get; set; }
        public string OVC_DAPPROVE { get; set; }
        public string OVC_KIND { get; set; }
        public string OVC_COMPTROLLER_NO { get; set; }
        public string OVC_DCOMPTROLLER { get; set; }
        public string OVC_DGARRENT_END { get; set; }
        public Nullable<short> ONB_NO { get; set; }
        public string OVC_ONNAME { get; set; }
        public string OVC_DGARRENT_START { get; set; }
        public System.Guid OVC_CASH_SN { get; set; }
    }
}
