//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMOVERSEE_LOG
    {
        public string OVC_PURCH { get; set; }
        public string OVC_DATE { get; set; }
        public string OVC_OVERSEE_UNIT { get; set; }
        public string OVC_APPLY_UNIT { get; set; }
        public string OVC_APPLY_NAME { get; set; }
        public string OVC_DAPPLY { get; set; }
        public string OVC_APPLY_NO { get; set; }
        public string OVC_APPLY_CHIEF { get; set; }
        public string OVC_APPLY_CHECK { get; set; }
    }
}
