//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMPURCH_EXT
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_PUR_NSECTION_2 { get; set; }
        public string IS_OEM_CONTRACT { get; set; }
        public string OEM_CONTRACT_KIND { get; set; }
        public string OEM_EXAMPLE_SUPPORT { get; set; }
        public string OVC_TARGET_KIND { get; set; }
        public string OVC_PERFORMANCE_PLACE { get; set; }
        public string OVC_PERFORMANCE_LIMIT { get; set; }
        public string OVC_VENDOR_DESC { get; set; }
        public string ORG_ID { get; set; }
        public string OVC_PUR_TAX_REASON { get; set; }
    }
}
