//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMPAY_MONEY
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_VEN_CST { get; set; }
        public short ONB_TIMES { get; set; }
        public string OVC_POI_IBDG { get; set; }
        public string OVC_PJNAME { get; set; }
        public string OVC_IBDG_USE { get; set; }
        public string OVC_IBDG_USE_NAME { get; set; }
        public string OVC_PAY_REASON { get; set; }
        public string OVC_PERFORMANCE_LIMIT { get; set; }
        public string OVC_DELIVERY_PLACE { get; set; }
        public string OVC_DFINISH { get; set; }
        public string OVC_DINSPECT_BEGIN { get; set; }
        public string OVC_DINSPECT_END { get; set; }
        public Nullable<short> ONB_DELAY_DAYS { get; set; }
        public Nullable<short> ONB_NO_PUNISH_DAYS { get; set; }
        public string OVC_NO_PUNISH_DAYS { get; set; }
        public Nullable<int> ONB_PUNISH_DAYS { get; set; }
        public Nullable<decimal> ONB_DELAY_MONEY { get; set; }
        public Nullable<decimal> ONB_OTHER_MONEY { get; set; }
        public string OVC_CURRENT { get; set; }
        public Nullable<decimal> ONB_RATE { get; set; }
        public Nullable<decimal> ONB_MCONTRACT { get; set; }
        public Nullable<decimal> ONB_MINS_MONEY { get; set; }
        public Nullable<decimal> ONB_PAY_MONEY { get; set; }
        public string OVC_ADVICE { get; set; }
        public string OVC_SUMMARY { get; set; }
        public Nullable<decimal> ONB_ADD_MONEY_1 { get; set; }
        public string OVC_ADD_ACCORDING_1 { get; set; }
        public Nullable<decimal> ONB_ADD_MONEY_2 { get; set; }
        public string OVC_ADD_ACCORDING_2 { get; set; }
        public Nullable<decimal> ONB_MINS_MONEY_1 { get; set; }
        public string OVC_MINS_ACCORDING_1 { get; set; }
        public Nullable<decimal> ONB_MINS_MONEY_2 { get; set; }
        public string OVC_MINS_ACCORDING_2 { get; set; }
        public string OVC_DO_NAME { get; set; }
        public string OVC_DPAY { get; set; }
        public Nullable<decimal> ONB_INSPECT_MONEY { get; set; }
    }
}
