//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMRECEIVE_ANNOUNCE
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_TARGET_KIND { get; set; }
        public string OVC_PURCH_TYPE { get; set; }
        public string OVC_LAW_NO { get; set; }
        public string OVC_READ_BID { get; set; }
        public string OVC_COMMON_BUY { get; set; }
        public string OVC_EOBTAIN { get; set; }
        public Nullable<short> ONB_DOC_MONEY { get; set; }
        public string OVC_ESUBMIT { get; set; }
        public string OVC_BID_TYPE { get; set; }
        public string OVC_WTO { get; set; }
        public string OVC_GPA_ENGLISH { get; set; }
        public string OVC_NOGPA_REASON { get; set; }
        public string OVC_NAME { get; set; }
        public string OVC_TELEPHONE { get; set; }
        public string OVC_FAX { get; set; }
        public string OVC_BUDGET_OPEN { get; set; }
        public string OVC_DBID_LIMIT { get; set; }
        public string OVC_LIMIT_HOUR { get; set; }
        public string OVC_LIMIT_MIN { get; set; }
        public string OVC_DOPEN { get; set; }
        public string OVC_OPEN_HOUR { get; set; }
        public string OVC_OPEN_MIN { get; set; }
        public short ONB_TIMES { get; set; }
        public string OVC_PLACE { get; set; }
        public string OVC_BID_LANGUAGE { get; set; }
        public string OVC_PERFORMANCE_PLACE { get; set; }
        public string OVC_PERFORMANCE_LIMIT { get; set; }
        public string OVC_RECEIVE_PLACE { get; set; }
        public string OVC_VENDOR_DESC { get; set; }
        public string OVC_DOC_PLACE { get; set; }
        public Nullable<short> ONB_BID_SELL { get; set; }
        public string OVC_DQUESTION { get; set; }
        public string OVC_DESC { get; set; }
        public string OVC_DANNOUNCE { get; set; }
        public string OVC_DAPPROVE { get; set; }
        public string OVC_DSEND { get; set; }
        public string OVC_SPECIAL { get; set; }
        public string OVC_BUDGET_BUY { get; set; }
        public string OVC_RESERVE_AMOUNT { get; set; }
        public string OVC_BUY_RANK { get; set; }
        public string OVC_DRAFT_COMM { get; set; }
        public string OVC_BID_METHOD_1 { get; set; }
        public string OVC_BID_METHOD_2 { get; set; }
        public string OVC_BID_METHOD_3 { get; set; }
        public string OVC_TXT_FILE { get; set; }
    }
}
