//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMRECEIVE_WORK
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_DANNOUNCE { get; set; }
        public string OVC_DSELL { get; set; }
        public string OVC_SELL_HOUR { get; set; }
        public string OVC_SELL_MIN { get; set; }
        public string OVC_DOPEN { get; set; }
        public string OVC_OPEN_HOUR { get; set; }
        public string OVC_OPEN_MIN { get; set; }
        public short ONB_TIMES { get; set; }
        public string OVC_CHAIRMAN { get; set; }
        public string OVC_DWAIT { get; set; }
        public string OVC_DWAIT_KIND { get; set; }
        public string OVC_DESC { get; set; }
        public string OVC_MEETING { get; set; }
        public string OVC_ADVICE { get; set; }
        public string OVC_DAPPROVE { get; set; }
        public string OVC_PUR_ASS_VEN_CODE { get; set; }
        public string OVC_BID_MONEY { get; set; }
    }
}
