//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMRECEIVE_ANNOUNCE_ENG
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_DOPEN { get; set; }
        public short ONB_TIMES { get; set; }
        public string OVC_ENTITY_CODE { get; set; }
        public string OVC_BID_TYPE { get; set; }
        public string OVC_WHETHER_GPA { get; set; }
        public string OVC_PROCURING_ENTITY { get; set; }
        public string OVC_PROCURING_ADDRESS { get; set; }
        public string OVC_PUR_IPURCH_ENG { get; set; }
        public string OVC_TARGET_KIND { get; set; }
        public string OVC_NAME { get; set; }
        public string OVC_TELEPHONE { get; set; }
        public string OVC_BID_SELL { get; set; }
        public string OVC_DOC_PLACE { get; set; }
        public string OVC_DBID_LIMIT { get; set; }
        public string OVC_DESC { get; set; }
    }
}
