//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMRECEIVE_ANNOUNCE_EXT
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_DOPEN { get; set; }
        public short ONB_TIMES { get; set; }
        public string EMAIL { get; set; }
        public string OVC_BUDGET_NOTOPEN_REASON { get; set; }
        public string OVC_TELEPHONE_AREA { get; set; }
        public string OVC_TELEPHONE_EXT { get; set; }
        public string OVC_FAX_AREA { get; set; }
        public string IS_PACKAGE { get; set; }
        public string IS_LOWEST_LAW { get; set; }
        public string IS_ENGINEER { get; set; }
        public string IS_PHY_OBTAIN { get; set; }
        public string IS_PHY_GRANT { get; set; }
        public string IS_RULE_104_105 { get; set; }
        public string IS_RULE_104_105_REASON { get; set; }
        public string IS_PRIORITY { get; set; }
        public string PRIORITY_CATE1 { get; set; }
        public string PRIORITY_CATE2 { get; set; }
        public string NOOBTAINREASON { get; set; }
        public string BID_WAY { get; set; }
        public string TENDER_BIDSTR { get; set; }
        public string PRE_TENDER_CASE_NO { get; set; }
        public string TARGET_DATE90 { get; set; }
        public string SPDT180_REASON { get; set; }
        public string CHECK_QUALIFICATION { get; set; }
        public string TENDER_LIST_VALID_TIME_START { get; set; }
        public string TENDER_LIST_VALID_TIME_END { get; set; }
        public string TENDER_LIST_EXTEND { get; set; }
        public string TENDER_LIST_NAME { get; set; }
        public string TENDER_DOC_NO { get; set; }
        public string READBID_CASE_NO { get; set; }
        public string IS_SPECIAL_BUDGET { get; set; }
        public string SPECIAL_BUDGET_TYPE { get; set; }
        public string SPECIAL_BUDGET { get; set; }
        public string DC_IDSTR { get; set; }
        public string DC_OIDSTRR { get; set; }
        public string DEPT_CHARGE { get; set; }
        public string DOC_CHARGE { get; set; }
        public string IS_ADAPT_LAW99 { get; set; }
        public string IS_GAZETTE { get; set; }
        public string OVC_DOC_PLACE { get; set; }
        public string TENDER_LC_EXPR_DATE { get; set; }
    }
}
