//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMRECEIVE_BID
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_DRECEIVE { get; set; }
        public string OVC_NAME { get; set; }
        public string OVC_NAME_RESULT { get; set; }
        public string OVC_DO_NAME { get; set; }
        public string OVC_DO_NAME_RESULT { get; set; }
        public string OVC_DAPPROVE { get; set; }
        public string OVC_DO_DAPPROVE { get; set; }
        public string OVC_REJECT_REASON { get; set; }
        public string OVC_REJECT_REASON_DO { get; set; }
    }
}
