//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMRECEIVE_CONTRACT
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_VEN_CST { get; set; }
        public short ONB_GROUP { get; set; }
        public string OVC_DRECEIVE { get; set; }
        public Nullable<short> ONB_SHIP_TIMES { get; set; }
        public string OVC_CLOSE { get; set; }
        public string OVC_STATUS { get; set; }
        public string OVC_DCLOSE { get; set; }
        public string OVC_DO_NAME { get; set; }
        public string OVC_GRANT_TO { get; set; }
        public string OVC_PUR_GOOD_OK { get; set; }
        public string OVC_PUR_TAX_OK { get; set; }
        public string OVC_PUR_FEE_OK { get; set; }
        public string OVC_RECEIVE_COMM { get; set; }
        public string OVC_INSPECT { get; set; }
        public string OVC_COMMAND1 { get; set; }
        public string OVC_COMMAND2 { get; set; }
        public string OVC_VEN_CELLPHONE { get; set; }
        public string OVC_VEN_FAX { get; set; }
        public string OVC_VEN_EMAIL { get; set; }
        public string OVC_USER_FAX { get; set; }
        public string OVC_VEN_TITLE { get; set; }
        public string OVC_VEN_TEL { get; set; }
        public string OVC_VEN_ADDRESS { get; set; }
        public Nullable<decimal> ONB_MONEY { get; set; }
        public string OVC_PUR_NSECTION { get; set; }
        public string OVC_PUR_USER { get; set; }
        public string OVC_PUR_IUSER_PHONE { get; set; }
        public string OVC_PUR_IUSER_PHONE_EXT { get; set; }
        public string OVC_USER_CELLPHONE { get; set; }
        public string OVC_CONTRACT_DELAY { get; set; }
        public string OVC_DELAY_REASON { get; set; }
        public string OVC_RESERVE { get; set; }
        public string OVC_RESERVE_REASON { get; set; }
        public string OVC_DCONTRACT { get; set; }
    }
}
