//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMRESULT_ANNOUNCE
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_ANNOUNCE_KIND { get; set; }
        public string OVC_PUR_ASS_VEN_CODE { get; set; }
        public string OVC_PART_IPURCH { get; set; }
        public string OVC_TARGET_KIND { get; set; }
        public string OVC_PERFORMANCE_PLACE { get; set; }
        public string OVC_LAW_58 { get; set; }
        public string OVC_STATUS { get; set; }
        public string OVC_DBID { get; set; }
        public string OVC_PUR_CURRENT { get; set; }
        public Nullable<decimal> ONB_PUR_BUDGET { get; set; }
        public string OVC_BID_CURRENT { get; set; }
        public Nullable<decimal> ONB_BID_BUDGET { get; set; }
        public string OVC_RESULT_CURRENT { get; set; }
        public Nullable<decimal> ONB_BID_RESULT { get; set; }
        public Nullable<short> ONB_BID_VENDORS { get; set; }
        public Nullable<short> ONB_RESULT_VENDORS { get; set; }
        public string OVC_NONE_VENDORS { get; set; }
        public string OVC_DESC { get; set; }
        public string OVC_NAME { get; set; }
        public string OVC_DAPPROVE { get; set; }
        public string OVC_DSEND { get; set; }
    }
}
