//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDELIVERY
    {
        public string PURCH { get; set; }
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_PUR_AGENCY { get; set; }
        public short ONB_GROUP { get; set; }
        public string OVC_PUR_IPURCH { get; set; }
        public string OVC_PUR_NSECTION { get; set; }
        public string OVC_LAB { get; set; }
        public Nullable<decimal> ONB_MONEY { get; set; }
        public string OVC_DCONTRACT { get; set; }
        public string OVC_DCLOSE { get; set; }
        public string OVC_STATUS { get; set; }
        public string OVC_RECEIVE_COMM { get; set; }
        public string OVC_GRANT_TO { get; set; }
        public string OVC_DO_NAME { get; set; }
        public string OVC_VEN_TITLE { get; set; }
        public string OVC_CLOSE { get; set; }
    }
}
