//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCFDFE.Entity.MPMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VITBM1302
    {
        public string OVC_PURCH { get; set; }
        public string OVC_PURCH_6 { get; set; }
        public string OVC_PURCH_5 { get; set; }
        public short ONB_GROUP { get; set; }
        public string OVC_VEN_CST { get; set; }
        public string OVC_VEN_TITLE { get; set; }
        public string OVC_VEN_TEL { get; set; }
        public string OVC_VEN_ADDRESS { get; set; }
        public string OVC_BUD_CURRENT { get; set; }
        public Nullable<decimal> ONB_BUD_RATE { get; set; }
        public Nullable<decimal> ONB_BUD_MONEY { get; set; }
        public string OVC_CURRENT { get; set; }
        public Nullable<decimal> ONB_RATE { get; set; }
        public Nullable<decimal> ONB_MONEY { get; set; }
        public Nullable<decimal> ONB_MONEY_DISCOUNT { get; set; }
        public string OVC_DCONTRACT { get; set; }
        public string OVC_SHIP_TIMES { get; set; }
        public string OVC_RECEIVE_PLACE { get; set; }
        public string OVC_PAYMENT { get; set; }
        public string OVC_CONTRACT_COMM { get; set; }
        public string OVC_DBID { get; set; }
        public Nullable<short> ONB_DELIVERY_TIMES { get; set; }
        public string OVC_NAME { get; set; }
        public string OVC_DOPEN { get; set; }
        public string OVC_DSEND { get; set; }
        public string OVC_DRECEIVE { get; set; }
        public string OVC_PROCUMENT_NO { get; set; }
        public string OVC_VEN_FAX { get; set; }
        public string OVC_VEN_EMAIL { get; set; }
        public string OVC_VEN_BOSS { get; set; }
        public string OVC_VEN_NAME { get; set; }
        public string OVC_VEN_CELLPHONE { get; set; }
    }
}
